C ========================================================================
C	SUBROUTINE GEN_HKLS_LSQ(HKLS_OUT,PIXWAV_OUT,NHKLS, WAV_MIN,D_MIN)
C	SUBROUTINE GEN_HKLS_FULL(HKLS,PIXWAVS,NHKLS, UB,WAV_MIN,D_MIN)
C	SUBROUTINE GEN_HKLS_SIMPLE(HKLS,PIXWAV,NHKLS, UB,HSQ_MAX,WAV_MIN)
C	LOGICAL FUNCTION IS_MULTIPLE(IH,IK,IL)
C ========================================================================


	SUBROUTINE GEN_HKLS_LSQ(HKLS_OUT,PIXWAV_OUT,NHKLS, WAV_MIN,D_MIN)
C
	REAL HKLS_OUT(3,*),PIXWAV_OUT(3,*)
C
	REAL UB(3,3)
C
	CALL CALC_UB_MATRIX(UB)
C
	CALL GEN_HKLS_FULL(HKLS_OUT,PIXWAV_OUT,NHKLS, UB,WAV_MIN,D_MIN)
C
	RETURN
	END


	SUBROUTINE GEN_HKLS_FULL(HKLS,PIXWAVS,NHKLS, UB,WAV_MIN,D_MIN)
C
C Copy a list of unique hkls obeying the minimum d-spacing
C and wavelength and which strike within the detector limits.
C
	REAL HKLS(3,*),PIXWAVS(3,*),UB(3,3)
C
	COMMON /PIXEL_COM/ PIX_CEN(2),PIX_SIZE(2),PIX_SKEW
	COMMON /OFFSETS_COM/ XTAL_OFF(3),DRUM_OFF(3),BEAM_VERT
	COMMON /GEOM_COM/ ITYPE,NUMX,NUMY,DRUM_RAD,PHI
C
	PARAMETER (NHKLS_MAX=300000)
	INTEGER IMULTS(NHKLS_MAX),IHKLS(3,NHKLS_MAX),IMODS(NHKLS_MAX)
C
C Generate the hkl list, giving some info as we go
C
	CALL GEN_HEMISPHERE(HKLS,NHKLS, UB,ICEN,D_MIN,1E6)
	PRINT '(1X,I8,A)',NHKLS,' hkls generated in a hemisphere'
C
	CALL PRUNE_XY_WAV(HKLS,IHKLS,IMODS,NHKLS, UB, 1.0,FLOAT(NUMX), 1.0,FLOAT(NUMY), WAV_MIN,1E6)
	PRINT '(1X,I8,A)',NHKLS,' hkls after pruning to X,Y, and wavelength limits'
C
	CALL PRUNE_MULTIPLES(HKLS,IHKLS,IMODS,IMULTS,NHKLS, UB)
	PRINT '(1X,I8,A)',NHKLS,' hkls after pruning multiples'
C
	CALL CALC_HKLS_TO_PIXWAVS(PIXWAVS, UB,HKLS,NHKLS)
C
	RETURN
	END


	SUBROUTINE GEN_HKLS_SIMPLE(HKLS,PIXWAV,NHKLS, UB,HSQ_MAX,WAV_MIN)
C
C Generate a hkl-list (ignoring lattice centering)
C where |H|^2 <= HSQ_MAX and WAV > WAV_MIN
C
	REAL HKLS(3,*),PIXWAV(3,*),UB(3,3)
C
	COMMON /GEOM_COM/ ITYPE,NUMX,NUMY,DRUM_RAD,PHI
C
	LOGICAL IS_MULTIPLE
C
	IHKL_MAX=INT(SQRT(HSQ_MAX)+0.01)
	NHKLS=0
	DO IH=0,IHKL_MAX
	  DO IK=-IHKL_MAX,IHKL_MAX
	    DO IL=-IHKL_MAX,IHKL_MAX
C Ignore |h|^2 > hsq_max
	      IF(FLOAT(IH*IH+IK*IK+IL*IL) .GT. HSQ_MAX+0.01) CYCLE
C Ignore 0,0,0 and Friedel pairs
	      IF(IH .EQ. 0) THEN
	        IF(IK .LT. 0) CYCLE
	        IF(IK.EQ.0 .AND. IL.LE.0) CYCLE
	      ENDIF
C Add hkl to the list if it not a multiple
	      IF( .NOT.IS_MULTIPLE(IH,IK,IL) ) THEN
	        NHKLS=NHKLS+1
	        HKLS(1,NHKLS)=IH
	        HKLS(2,NHKLS)=IK
	        HKLS(3,NHKLS)=IL
	      ENDIF
C
	    ENDDO
	  ENDDO
	ENDDO
C
	CALL CALC_HKLS_TO_PIXWAVS(PIXWAV, UB,HKLS,NHKLS)
C
	N=0
	DO I=1,NHKLS
	  IF(PIXWAV(1,I).LT.10.0 .OR. PIXWAV(1,I).GT.NUMX-10.0 .OR. 
	1     PIXWAV(2,I).LT.10.0 .OR. PIXWAV(2,I).GT.NUMY-10.0 .OR.
	2	   ABS(PIXWAV(3,I)).LT.WAV_MIN                        ) CYCLE
	  N=N+1
	  ISIGN=+1
	  IF(PIXWAV(3,I) .LT. 0.0) ISIGN=-1
	  HKLS(1,N)=HKLS(1,I)*ISIGN
	  HKLS(2,N)=HKLS(2,I)*ISIGN
	  HKLS(3,N)=HKLS(3,I)*ISIGN
	  PIXWAV(1,N)=PIXWAV(1,I)
	  PIXWAV(2,N)=PIXWAV(2,I)
	  PIXWAV(3,N)=PIXWAV(3,I)*ISIGN
	ENDDO
C
	NHKLS=N
	RETURN
	END


	LOGICAL FUNCTION IS_MULTIPLE(IH,IK,IL)
C
	INTEGER IPRIMES(5)
	DATA IPRIMES/2,3,5,7,11/
C
	IMAX=MAX(ABS(IH),ABS(IK),ABS(IL))
C
	IF(IMAX .GT. 11) CALL QUIT('BUG(is_multiple): IMAX > 11')
C
	IMIN=MIN(ABS(IH),ABS(IK),ABS(IL))
	IMED=ABS(IH)+ABS(IK)+ABS(IL)-IMAX-IMIN
C
	DO I=1,5
	  IP=IPRIMES(I)
	  IF(IP.GT. IMAX) EXIT
	  IF(IMAX .NE. IMAX/IP*IP) CYCLE
	  IF(IMED .NE. IMED/IP*IP) CYCLE
	  IF(IMIN .NE. IMIN/IP*IP) CYCLE
	  IS_MULTIPLE=.TRUE.
	  RETURN
	ENDDO
C
	IS_MULTIPLE=.FALSE.
	RETURN
	END
