C----- Sets parameters to initial values ---------------------------
c	SUBROUTINE INIT_FILE_PARS
c	SUBROUTINE INIT_TWINS_PARS
c	SUBROUTINE INIT_WAV_PARS
c	SUBROUTINE INIT_EFF_PARS
c	SUBROUTINE INIT_ABS_PARS
c	SUBROUTINE INIT_EXTI_PARS
C----- Set parameters to refine (or not) ---------------------------
c	SUBROUTINE REFINE_FILE_PARS(LFILE0)
c	SUBROUTINE REFINE_TWIN_PARS
c	SUBROUTINE REFINE_WAV_PARS(LWAV0)
c	SUBROUTINE REFINE_EFF_PARS(LEFF0)
c	SUBROUTINE REFINE_ABS_PARS(LABS0)
c	SUBROUTINE REFINE_EXTI_PARS(LEXTI0)
C----- High-level routines to pack/unpack LSQ parameters -----------
c	SUBROUTINE PACK_LSQ_PARS(PARS,NPARS)
c	SUBROUTINE UNPACK_LSQ_PARS(PARS,ESDS,LPRINT)
c	SUBROUTINE GET_PAR_NAME(NAME, IPAR)
C----- Low-level routines to pack/unpack LSQ parameters ------------
c	SUBROUTINE PACK_FILE_PARS(PARS,IPAR)
c	SUBROUTINE UNPACK_FILE_PARS(IPAR, PARS,ESDS,LPRINT)
c	SUBROUTINE PACK_TWINS_PARS(PARS,IPAR)
c	SUBROUTINE UNPACK_TWINS_PARS(IPAR, PARS,ESDS,LPRINT)
c	SUBROUTINE PACK_WAV_PARS(PARS,IPAR)
c	SUBROUTINE UNPACK_WAV_PARS(IPAR, PARS,ESDS,LPRINT)
c	SUBROUTINE PACK_EFF_PARS(PARS,IPAR)
c	SUBROUTINE UNPACK_EFF_PARS(IPAR, PARS,ESDS,LPRINT)
c	SUBROUTINE PACK_ABS_PARS(PARS,IPAR)
c	SUBROUTINE UNPACK_ABS_PARS(IPAR, PARS,ESDS,LPRINT)
c	SUBROUTINE PACK_EXTI_PARS(PARS,IPAR)
c	SUBROUTINE UNPACK_EXTI_PARS(IPAR, PARS,ESDS,LPRINT)
C-------------------------------------------------------------------


C----- Sets parameters to initial values ---------------------------

	SUBROUTINE INIT_FILE_PARS
C
	LOGICAL LFILE_CORR,LWAV_CORR,LEFF_CORR,LEXTI_CORR,LHARM_CORR,LABS_CORR
	COMMON /LCORR_COM/ LFILE_CORR,LWAV_CORR,LEFF_CORR,LEXTI_CORR,LHARM_CORR,LABS_CORR
C
	PARAMETER (NFILES_MAX=400)
	COMMON /FILE_CORR_COM/ FSCALE(NFILES_MAX)
C
	COMMON /FILE_NUM_COM/ IFILE_NUM(NFILES_MAX),NFILES
C
C Store if we use this correction, if not return immediately
C
	IF( .NOT.LFILE_CORR ) RETURN
C
C Initialise file scale factors to 1.0
C
	DO I=1,NFILES
	  FSCALE(I)=1.0
	ENDDO
C
	RETURN
	END



	SUBROUTINE INIT_TWINS_PARS
C
      LOGICAL LTWIN1,LTWIN2,LTWIN11,LTWIN12,LRATIO
      COMMON /TWINS_CORR_COM/ ITWIN_OPT,TWIN_RATIO,LTWIN1,LTWIN2,LTWIN11,LTWIN12,LRATIO
C
C Always initialise twin ratio to 1.0
C
cccccccccccccc???????????????????>>>>>>>>>>>>>>>>>>	TWIN_RATIO=1.0
	TWIN_RATIO=0.6
C
	RETURN
	END



	SUBROUTINE INIT_WAV_PARS
C
	PARAMETER (NDATA_MAX=2000000)
	INTEGER HKLMS(4,NDATA_MAX),IFILES(NDATA_MAX)
	REAL WAVS(NDATA_MAX),COUNTS(NDATA_MAX),DCOUNTS(NDATA_MAX)
	REAL TTHS(NDATA_MAX),XY_PIX(2,NDATA_MAX)
	COMMON /DATA_COM/ HKLMS,IFILES,WAVS,COUNTS,DCOUNTS,TTHS,XY_PIX,NDATA
C
	PARAMETER (NSEQ_MAX=100000)
	COMMON /SEQ_COM/ IFIRST(NSEQ_MAX),ILAST(NSEQ_MAX),COUNTS_SEQ(NSEQ_MAX),NSEQ
C
	LOGICAL LFILE_CORR,LWAV_CORR,LEFF_CORR,LEXTI_CORR,LHARM_CORR,LABS_CORR
	COMMON /LCORR_COM/ LFILE_CORR,LWAV_CORR,LEFF_CORR,LEXTI_CORR,LHARM_CORR,LABS_CORR
C
	COMMON /WAV_CORR_COM/ IWAV_OPT,NWAV,WAV_GAMMA,WAV_MIN,WAV_STEP,WAV_PAR(20)
C
C If correction is off, return immediately
C
	IF( .NOT.LWAV_CORR ) RETURN
C
C Find the wavelength range for all reflections in all sequences
C
	WAV_MIN=1E6
	WAV_MAX=-1E6
	DO ISEQ=1,NSEQ
	  DO I=IFIRST(ISEQ),ILAST(ISEQ)
	    WAV_MIN=MIN(WAV_MIN, WAVS(I) )
	    WAV_MAX=MAX(WAV_MAX, WAVS(I) )
	  ENDDO
	ENDDO
C
C Calculate the wavelength step-size for spline with NWAV points
C
	WAV_STEP=(WAV_MAX-WAV_MIN)/(NWAV-1)
C
C Initialise refineable parameters to 1.0
C
	DO I=1,NWAV
	  WAV_PAR(I)=1.0
	ENDDO
C
	RETURN
	END



	SUBROUTINE INIT_EFF_PARS
C
C Disable correction (for INITIAL_FILE_SCALES)
C
	LOGICAL LFILE_CORR,LWAV_CORR,LEFF_CORR,LEXTI_CORR,LHARM_CORR,LABS_CORR
	COMMON /LCORR_COM/ LFILE_CORR,LWAV_CORR,LEFF_CORR,LEXTI_CORR,LHARM_CORR,LABS_CORR
C
	COMMON /EFF_CORR_COM/ IEFF_OPT,EFF_POLY(10)
C
C If no efficiency corrections, set EFF_POLY to zero and return
C
	IF( .NOT.LEFF_CORR ) THEN
	  DO I=1,IEFF_OPT
	    EFF_POLY(I)=0.0
	  ENDDO
	  RETURN
	ENDIF
C
	DO I=1,IEFF_OPT
	  EFF_POLY(I)=0.05
	ENDDO
C
	RETURN
	END



	SUBROUTINE INIT_ABS_PARS
C
C Disable correction (for INITIAL_FILE_SCALES)
C
	LOGICAL LFILE_CORR,LWAV_CORR,LEFF_CORR,LEXTI_CORR,LHARM_CORR,LABS_CORR
	COMMON /LCORR_COM/ LFILE_CORR,LWAV_CORR,LEFF_CORR,LEXTI_CORR,LHARM_CORR,LABS_CORR
C
	COMMON /ABS_CORR_COM/ IABS_OPT,UR0,UR_LIN
C
C If no absorption correction, set uR to zero and return
C
	IF( .NOT.LABS_CORR ) THEN
		UR0=0.0
		UR_LIN=0.0
	  RETURN
	ENDIF
C
C Setup UR0 & UR_LIN as if set by UNPACK_ABS_PARS
C
	UR0=0.1
	UR_LIN=0.1
C IABS_OPT=1	normal absorbers
	IF(IABS_OPT .EQ. 1) UR0=0.0
C IABS_OPT=2	hydrogen, Judith Howard's eqn (19.2*WAV+20.6 barns)
	IF(IABS_OPT .EQ. 2) UR0=UR_LIN*1.07
C
	RETURN
	END



	SUBROUTINE INIT_EXTI_PARS
C
C We must first calculate COUNTS_SEQ (with extinction off) before
C we can estimate the initial value for EXTI
C
	LOGICAL LFILE_CORR,LWAV_CORR,LEFF_CORR,LEXTI_CORR,LHARM_CORR,LABS_CORR
	COMMON /LCORR_COM/ LFILE_CORR,LWAV_CORR,LEFF_CORR,LEXTI_CORR,LHARM_CORR,LABS_CORR
C
	COMMON /EXTI_CORR_COM/ IEXTI_OPT,EXTI
C
	COMMON /MISC_PARS_COM/ NSEQ_MIN,SEQ_FRAC,X_LO,X_HI,Y_LO,Y_HI,WAV_LO,WAV_HI,
	1	CELL_MULT,EFF_WIDTH,EFF_THICK,EXTI_CORR_MAX,NBINS_NPAR,
	2	ALL_REL_ERR,ALL_SIG_MULT,WEAK_SIG_MULT,EXTI_ERR,WAV_ERR1,WAV_ERR2,
	3	HARM_CUTOFF_MULT,IVERBOSE
C
	PARAMETER (NSEQ_MAX=100000)
	COMMON /SEQ_COM/ IFIRST(NSEQ_MAX),ILAST(NSEQ_MAX),COUNTS_SEQ(NSEQ_MAX),NSEQ
C
	PARAMETER (NDATA_MAX=2000000)
	INTEGER HKLMS(4,NDATA_MAX),IFILES(NDATA_MAX)
	REAL WAVS(NDATA_MAX),COUNTS(NDATA_MAX),DCOUNTS(NDATA_MAX)
	REAL TTHS(NDATA_MAX),XY_PIX(2,NDATA_MAX)
	COMMON /DATA_COM/ HKLMS,IFILES,WAVS,COUNTS,DCOUNTS,TTHS,XY_PIX,NDATA
C
C If no extinction correction, set EXTI to zero and return
C
	IF( .NOT.LEXTI_CORR ) THEN
	  EXTI=0.0
	  RETURN
	ENDIF
C
C Get the largest extinction "x" factor for EXTI=1
C
	EXTI=1.0
	X_MAX=0.0
	DO ISEQ=1,NSEQ
	  DO I=IFIRST(ISEQ),ILAST(ISEQ)
	    X=CALC_EXTI_FACTOR(COUNTS_SEQ(ISEQ),WAVS(I),TTHS(I))
	    X_MAX=MAX(X_MAX, X )
	  ENDDO
	ENDDO
C
C Calculate what value of EXTI would give this correction
C
	EXTI=( (1.0+EXTI_CORR_MAX)**2 - 1.0)/X_MAX
C
	WRITE(10,'(A,2P,F5.1,A)') 'Estimated extinction parameter for '//
	1							'a max. correction of',EXTI_CORR_MAX,'%'
C
	RETURN
	END



C----------------- Set parameters to refine (or not) ---------------

	SUBROUTINE REFINE_FILE_PARS(LFILE0)
C
	LOGICAL LFILE0
C
	LOGICAL LFILE,LWAV,LEFF,LABS,LEXTI,LTWIN_RATIO
	COMMON /LSQ_LPAR_COM/ LFILE,LWAV,LEFF,LABS,LEXTI,LTWIN_RATIO
C
C Store switch to refine parameters
C
	LFILE=LFILE0
C
	IF(LFILE) THEN
	  PRINT '(1X,A)','Refining scale factors for each image file'
	  WRITE(10,'(A)') 'Refining scale factors for each image file'
	ELSE
	  WRITE(10,'(A)') 'Using equal scale factors for all image files'
	ENDIF
C
	RETURN
	END


	SUBROUTINE REFINE_TWIN_PARS
C
      LOGICAL LTWIN1,LTWIN2,LTWIN11,LTWIN12,LRATIO
      COMMON /TWINS_CORR_COM/ ITWIN_OPT,TWIN_RATIO,LTWIN1,LTWIN2,LTWIN11,LTWIN12,LRATIO
C
	LOGICAL LFILE,LWAV,LEFF,LABS,LEXTI,LTWIN_RATIO
	COMMON /LSQ_LPAR_COM/ LFILE,LWAV,LEFF,LABS,LEXTI,LTWIN_RATIO
C
C Set switch to refine twin ratio parameter
C
	LTWIN_RATIO=(ITWIN_OPT .GT. 0) .AND. LRATIO
C
	IF(LTWIN_RATIO) THEN
	  PRINT '(1X,A)','Refining twin ratio'
	  WRITE(10,'(A)') 'Refining twin ratio'
	ENDIF
C
	RETURN
	END


	SUBROUTINE REFINE_WAV_PARS(LWAV0)
C
	LOGICAL LWAV0
C
	LOGICAL LFILE,LWAV,LEFF,LABS,LEXTI,LTWIN_RATIO
	COMMON /LSQ_LPAR_COM/ LFILE,LWAV,LEFF,LABS,LEXTI,LTWIN_RATIO
C
	LOGICAL LFILE_CORR,LWAV_CORR,LEFF_CORR,LEXTI_CORR,LHARM_CORR,LABS_CORR
	COMMON /LCORR_COM/ LFILE_CORR,LWAV_CORR,LEFF_CORR,LEXTI_CORR,LHARM_CORR,LABS_CORR
C
	COMMON /WAV_CORR_COM/ IWAV_OPT,NWAV,WAV_GAMMA,WAV_MIN,WAV_STEP,WAV_PAR(20)
C
C Store switch to refine parameters
C
	LWAV=LWAV0
C
	IF(LWAV) THEN
	  PRINT '(1X,A)','Refining wavelength correction'
	  WAV_MAX=WAV_MIN+WAV_STEP*(NWAV-1)
	  WRITE(10,'(3(A,F6.3))') 'Refining wavelength correction from',
	1							WAV_MIN,' to',WAV_MAX,' in steps of',WAV_STEP
	ELSE
	  WRITE(10,'(A)') 'Not refining wavelength distribution'
	ENDIF
C
	RETURN
	END


	SUBROUTINE REFINE_EFF_PARS(LEFF0)
C
	LOGICAL LEFF0
C
	LOGICAL LFILE,LWAV,LEFF,LABS,LEXTI,LTWIN_RATIO
	COMMON /LSQ_LPAR_COM/ LFILE,LWAV,LEFF,LABS,LEXTI,LTWIN_RATIO
C
C Store switch to refine parameters
C
	LEFF=LEFF0
C
	IF(LEFF) THEN
	  PRINT '(1X,A)','Refining efficiency correction factors'
	  WRITE(10,'(A)') 'Refining efficiency correction factors'
	ELSE
	  WRITE(10,'(A)') 'Not refining efficiency correction factors'
	ENDIF
C
	RETURN
	END


	SUBROUTINE REFINE_ABS_PARS(LABS0)
C
	LOGICAL LABS0
C
	LOGICAL LFILE,LWAV,LEFF,LABS,LEXTI,LTWIN_RATIO
	COMMON /LSQ_LPAR_COM/ LFILE,LWAV,LEFF,LABS,LEXTI,LTWIN_RATIO
C
	COMMON /ABS_CORR_COM/ IABS_OPT,UR0,UR_LIN
C
C Store switch to refine parameters
C
	LABS=LABS0
C
C Inform the user about the type of absorption correction
C
	IF(LABS) THEN
	  IF(IABS_OPT .EQ. 1) THEN
	    WRITE(10,'(A,F6.3,A)') 'Spherical absorption correction using uR =',
	1											UR_LIN,' * wav'
	  ELSE IF(IABS_OPT .EQ. 2) THEN
	    WRITE(10,'(A,F6.2,A)') 'Spherical absorption correction using uR =',
	1											UR_LIN,' * (wav + 1.07)'
	  ELSE IF(IABS_OPT .EQ. 3) THEN
	    WRITE(10,'(A,2(F6.2,A))') 'Spherical absorption correction using uR =',
	1											UR0,' +',UR_LIN,' * wav'
	  ENDIF
	  PRINT '(1X,A)','Refining absorption parameter(s)'
	  WRITE(10,'(A)') 'Refining absorption parameter(s)'
	ELSE
	  WRITE(10,'(A)') 'No absorption correction'
	ENDIF
C
	RETURN
	END


	SUBROUTINE REFINE_EXTI_PARS(LEXTI0)
C
	LOGICAL LEXTI0
C
	LOGICAL LFILE,LWAV,LEFF,LABS,LEXTI,LTWIN_RATIO
	COMMON /LSQ_LPAR_COM/ LFILE,LWAV,LEFF,LABS,LEXTI,LTWIN_RATIO
C
C Store switch to refine parameters
C
	LEXTI=LEXTI0

C Log if we are refining using an extinction correct
C
	IF(LEXTI) THEN
	  PRINT '(1X,A)','Refining extinction correction factors'
	  WRITE(10,'(A)') 'Refining extinction correction factors'
	ENDIF
C
	RETURN
	END


C--------------- High-level routines to pack/unpack LSQ parameters -------------

	SUBROUTINE PACK_LSQ_PARS(PARS,NPARS)
C
C Pack all refined LSQ parameters into PARS, also return
C the number of refined parameters in NPARS
C
	REAL PARS(*)
C
	LOGICAL LFILE,LWAV,LEFF,LABS,LEXTI,LTWIN_RATIO
	COMMON /LSQ_LPAR_COM/ LFILE,LWAV,LEFF,LABS,LEXTI,LTWIN_RATIO
C
	COMMON /PARS_NUM_COM/ NFILE,NWAV,NEFF,NABS,NEXTI,NTWIN
C
C Load LSQ parameters into PARS
C Also, save the end position of each set for use by GET_PAR_NAME
C
	NPARS=0
	IF( LFILE ) CALL PACK_FILE_PARS(PARS,NPARS)
	NFILE=NPARS
	IF( LWAV  ) CALL PACK_WAV_PARS (PARS,NPARS)
	NWAV=NPARS
	IF( LEFF ) CALL PACK_EFF_PARS(PARS,NPARS)
	NEFF=NPARS
	IF( LABS  ) CALL PACK_ABS_PARS (PARS,NPARS)
	NABS=NPARS
	IF( LEXTI ) CALL PACK_EXTI_PARS(PARS,NPARS)
	NEXTI=NPARS
	IF( LTWIN_RATIO ) CALL PACK_TWINS_PARS(PARS,NPARS)
	NTWIN=NPARS
C
	RETURN
	END


	SUBROUTINE UNPACK_LSQ_PARS(PARS,ESDS,LPRINT)
C
C Unpack all refined LSQ parameters from PARS.
C If LPRINT is true, print out refined parameter values and esds.
C
	LOGICAL LPRINT
	REAL PARS(500),ESDS(500)
C
	LOGICAL LFILE,LWAV,LEFF,LABS,LEXTI,LTWIN_RATIO
	COMMON /LSQ_LPAR_COM/ LFILE,LWAV,LEFF,LABS,LEXTI,LTWIN_RATIO
C
C Unpack the refined parameters and output the refined result and esds
C
	IPAR=0
	IF( LFILE ) CALL UNPACK_FILE_PARS(IPAR, PARS,ESDS,LPRINT)
	IF( LWAV  ) CALL UNPACK_WAV_PARS (IPAR, PARS,ESDS,LPRINT)
	IF( LEFF  ) CALL UNPACK_EFF_PARS (IPAR, PARS,ESDS,LPRINT)
	IF( LABS  ) CALL UNPACK_ABS_PARS (IPAR, PARS,ESDS,LPRINT)
	IF( LEXTI ) CALL UNPACK_EXTI_PARS(IPAR, PARS,ESDS,LPRINT)
	IF( LTWIN_RATIO ) CALL UNPACK_TWINS_PARS(IPAR, PARS,ESDS,LPRINT)
C
	RETURN
	END


	SUBROUTINE GET_PAR_NAME(NAME, IPAR)
C
	CHARACTER NAME*(*)
C
	COMMON /PARS_NUM_COM/ NFILE,NWAV,NEFF,NABS,NEXTI,NTWIN
C
	NAME=REPEAT(' ',LEN(NAME))
	IF(LEN(NAME) .LT. 5) STOP 'BUG(get_par_name): LEN(NAME) < 5'
C
	IF(IPAR .LE. NFILE) THEN
	  WRITE(NAME,'(A,I3)') 'File',IPAR
	ELSE IF(IPAR .LE. NWAV) THEN
	  WRITE(NAME,'(A,I2)') 'Wav',IPAR-NTWIN
	ELSE IF(IPAR .LE. NEFF) THEN
	  WRITE(NAME,'(A,I2)') 'Effic',IPAR-NWAV
	ELSE IF(IPAR .LE. NABS) THEN
	  WRITE(NAME,'(A,I2)') 'Abs',IPAR-NEFF
	ELSE IF(IPAR .LE. NEXTI) THEN
	  NAME='Exti'
	ELSE IF(IPAR .LE. NTWIN) THEN
	  NAME='Twin'
	ELSE
	  STOP 'BUG(get_par_name): Invalid IPAR'
	ENDIF
C
	RETURN
	END


C--------------- Low-level routines to pack/unpack LSQ parameters -------------

	SUBROUTINE PACK_FILE_PARS(PARS,IPAR)
C
C Add FSCALE() to PARS()
C
	REAL PARS(*)
C
	PARAMETER (NFILES_MAX=400)
	COMMON /FILE_CORR_COM/ FSCALE(NFILES_MAX)
C
	COMMON /FILE_NUM_COM/ IFILE_NUM(NFILES_MAX),NFILES
C
C Pack all but last FSCALE() into PARS()
C
	DO I=1,NFILES-1
	  IPAR=IPAR+1
	  PARS(IPAR)=FSCALE(I)
	ENDDO
C
	RETURN
	END


	SUBROUTINE UNPACK_FILE_PARS(IPAR, PARS,ESDS,LPRINT)
C
C Unpack FSCALE() from PARS() and optionally output the refined result
C
	LOGICAL LPRINT
	REAL PARS(*),ESDS(*)
C
	LOGICAL LFILE_CORR,LWAV_CORR,LEFF_CORR,LEXTI_CORR,LHARM_CORR,LABS_CORR
	COMMON /LCORR_COM/ LFILE_CORR,LWAV_CORR,LEFF_CORR,LEXTI_CORR,LHARM_CORR,LABS_CORR
C
	PARAMETER (NFILES_MAX=400)
	COMMON /FILE_CORR_COM/ FSCALE(NFILES_MAX)
	COMMON /FILE_NUM_COM/ IFILE_NUM(NFILES_MAX),NFILES
C
	CHARACTER STRING*80
	REAL TEMP(500)
C
	DO I=1,NFILES-1
	  IPAR=IPAR+1
	  FSCALE(I)=PARS(IPAR)
	  TEMP(I)=ESDS(IPAR)
	ENDDO
C
C If no print-out is required, simply return
C
	IF( .NOT.LPRINT ) RETURN
C
C Print out refined FSCALE values + esds
C
	WRITE(10,'(/,A,/)') 'Scale factors used for input files:'
	DO I=1,NFILES,10
	  I2=MIN(I+9,NFILES)
C Output lines for actual file numbers and scale factor values
	  WRITE(10,'(A,I6,9I7)') 'File #  ',(IFILE_NUM(K),K=I,I2)
	  WRITE(10,'(A,10F7.3)') 'Scale   ',(FSCALE(K),K=I,I2)
C "Write" esd values to STRING()
	  WRITE(STRING,'(10F7.3)') (TEMP(K),K=I,I2)
C Overwrite the last scale factor esd in STRING() with "fixed"
	  IF(I2 .EQ. NFILES) STRING(7*(I2-I)+1:7*(I2-I)+7)='  fixed'
C Output STRING()
	  WRITE(10,'(2A)') 'esd     ',STRING(1:7*(I2-I+1))
	ENDDO
C
	RETURN
	END


	SUBROUTINE PACK_TWINS_PARS(PARS,IPAR)
C
C Add TWIN_RATIO to PARS()
C
	REAL PARS(*)
C
      LOGICAL LTWIN1,LTWIN2,LTWIN11,LTWIN12,LRATIO
      COMMON /TWINS_CORR_COM/ ITWIN_OPT,TWIN_RATIO,LTWIN1,LTWIN2,LTWIN11,LTWIN12,LRATIO
C
      IF( .NOT.LRATIO ) RETURN
C
C Pack TWIN_RATIO into PARS()
C
      IPAR=IPAR+1
	PARS(IPAR)=TWIN_RATIO
C
	RETURN
	END


	SUBROUTINE UNPACK_TWINS_PARS(IPAR, PARS,ESDS,LPRINT)
C
C Unpack TWIN_RATIO from PARS() and optionally output the refined result
C
	LOGICAL LPRINT
	REAL PARS(*),ESDS(*)
C
      LOGICAL LTWIN1,LTWIN2,LTWIN11,LTWIN12,LRATIO
      COMMON /TWINS_CORR_COM/ ITWIN_OPT,TWIN_RATIO,LTWIN1,LTWIN2,LTWIN11,LTWIN12,LRATIO
C
      IF( .NOT.LRATIO ) RETURN
C
      IPAR=IPAR+1
	TWIN_RATIO=PARS(IPAR)
C
	IF(LPRINT) WRITE(10,'(/,A,F6.2,A,F5.2,A)')
	1		'Twin ratio (#2/#1) =',TWIN_RATIO,' (',ESDS(IPAR),')'
C
	RETURN
	END


	SUBROUTINE PACK_WAV_PARS(PARS,IPAR)
C
C Add WAV_PAR() to PARS()
C
	REAL PARS(*)
C
	COMMON /WAV_CORR_COM/ IWAV_OPT,NWAV,WAV_GAMMA,WAV_MIN,WAV_STEP,WAV_PAR(20)
C
C Quad spline (the middle parameter is not refined!)
C
	DO I=1,NWAV
	  IF(I .NE. NWAV/2) THEN
	    IPAR=IPAR+1
	    PARS(IPAR)=WAV_PAR(I)
	  ENDIF
	ENDDO
C
	RETURN
	END


	SUBROUTINE UNPACK_WAV_PARS(IPAR, PARS,ESDS,LPRINT)
C
C Unpack WAV_PAR() from PARS() and optionally output the refined results
C
	LOGICAL LPRINT
	REAL PARS(*),ESDS(*)
C
	COMMON /WAV_CORR_COM/ IWAV_OPT,NWAV,WAV_GAMMA,WAV_MIN,WAV_STEP,WAV_PAR(20)
C
	CHARACTER STRING*80
	REAL TEMP(200)
C
C Unpack PARS into WAV_PAR and put ESDS into TEMP
C NB: The middle parameter is not refined
C
	DO I=1,NWAV
	  IF(I .NE. NWAV/2) THEN
	    IPAR=IPAR+1
	    WAV_PAR(I)=PARS(IPAR)
	    TEMP(I)=ESDS(IPAR)
	  ENDIF
	ENDDO
C
C If no print-out is required, simply return
C
	IF( .NOT.LPRINT ) RETURN
C
C Print out refined values + esds
C
	WRITE(10,'(/,A,/)') 'Wavelength spline parameters:'
	DO I=1,NWAV,10
	  I2=MIN(I+9,NWAV)
C Output lines for wavelength and spline values
	  WRITE(10,'(A,10F7.3)') 'Wav     ',(WAV_MIN+WAV_STEP*(K-1),K=I,I2)
	  WRITE(10,'(A,10F7.3)') 'Spline  ',(WAV_PAR(K),K=I,I2)
C "Write" esd values to STRING()
	  WRITE(STRING,'(10F7.3)') (TEMP(K),K=I,I2)
C Overwrite the middle parameter esd in STRING() with "fixed"
	  IF(NWAV/2.GE.I .AND. NWAV/2.LE.I2)
	1					STRING(7*(NWAV/2-I)+1:7*(NWAV/2-I)+7)='  fixed'
C Output STRING()
	  WRITE(10,'(2A)') 'esd     ',STRING(1:7*(I2-I+1))
	ENDDO
C
	RETURN
	END


	SUBROUTINE PACK_EFF_PARS(PARS,IPAR)
C
C Add EFF parameters to PARS()
C
	REAL PARS(*)
C
	COMMON /EFF_CORR_COM/ IEFF_OPT,EFF_POLY(10)
C
	DO I=1,IEFF_OPT
	  IPAR=IPAR+1
	  PARS(IPAR)=EFF_POLY(I)
	ENDDO
C
	RETURN
	END


	SUBROUTINE UNPACK_EFF_PARS(IPAR, PARS,ESDS,LPRINT)
C
C Unpack YWAV parameters from PARS() and optionally output the refined result
C
	LOGICAL LPRINT
	REAL PARS(*),ESDS(*)
C
	COMMON /EFF_CORR_COM/ IEFF_OPT,EFF_POLY(10)
C
	IF( LPRINT .AND. (IEFF_OPT.GE.1) ) WRITE(10,'(/,A)') 'Efficiency parameters:'
	DO I=1,IEFF_OPT
	  IPAR=IPAR+1
	  EFF_POLY(I)=PARS(IPAR)
	  IF(LPRINT) WRITE(10,'(F10.4,A,F7.4,A)') PARS(IPAR),'(',ESDS(IPAR),')'
	ENDDO
C
	RETURN
	END


	SUBROUTINE PACK_ABS_PARS(PARS,IPAR)
C
C Add ABS to PARS()
C
	REAL PARS(*)
C
	COMMON /ABS_CORR_COM/ IABS_OPT,UR0,UR_LIN
C
C Always refine the wavelength dependent part
C
	IPAR=IPAR+1
	PARS(IPAR)=UR_LIN
C
C Only refine the constant part for the general case
C
	IF(IABS_OPT .EQ. 3) THEN
	  IPAR=IPAR+1
	  PARS(IPAR)=UR0
	ENDIF
C
	RETURN
	END


	SUBROUTINE UNPACK_ABS_PARS(IPAR, PARS,ESDS,LPRINT)
C
C Unpack EXTI from PARS() and optionally output the refined result
C
	LOGICAL LPRINT
	REAL PARS(*),ESDS(*)
C
	COMMON /ABS_CORR_COM/ IABS_OPT,UR0,UR_LIN
C
C Always refine the wavelength dependent part
C
	IPAR=IPAR+1
	UR_LIN=PARS(IPAR)
C
C Set UR0 depending on the model used
C
C IABS_OPT=1	normal absorbers
	IF(IABS_OPT .EQ. 1) THEN
	  UR0=0.0
C IABS_OPT=2	hydrogen, Judith Howard's eqn (19.2*WAV+20.6 barns)
	ELSE IF(IABS_OPT .EQ. 2) THEN
	  UR0=UR_LIN*1.07
C IABS_OPT=3	general case, UR0 & UR_LIN are indenpendent
	ELSE IF(IABS_OPT .EQ. 3) THEN
	  IPAR=IPAR+1
	  UR0=PARS(IPAR)
	ENDIF
C
	IF(LPRINT) THEN
	  IF(IABS_OPT .EQ. 1) THEN
	    WRITE(10,'(/,A,2(F6.3,A,F5.3,A))') 'Refined uR =',
	1							UR_LIN,' (',ESDS(IPAR),') * wav'
	    IFRAC_H=0
	  ELSE IF(IABS_OPT .EQ. 2) THEN
	    WRITE(10,'(/,A,2(F6.2,A,F5.2,A))') 'Refined uR =',
	1							UR_LIN,' (',ESDS(IPAR),') * (wav + 1.07)'
	    IFRAC_H=100
	  ELSE IF(IABS_OPT .EQ. 3) THEN
	    WRITE(10,'(/,A,2(F6.2,A,F5.2,A))') 'Refined uR =',
	1		UR0,' (',ESDS(IPAR-1),') +',UR_LIN,' (',ESDS(IPAR),') * wav'
	    IFRAC_H= NINT( 100.0*UR0/1.07/MAX(1E-8,UR_LIN) )
	  ENDIF
	  WRITE(10,'(2X,A,I4,A)') 'Fraction of "hydrogenous absorption" =',
	1								MAX(-999,MIN(+999, IFRAC_H)),'%'
	ENDIF
C
	RETURN
	END


	SUBROUTINE PACK_EXTI_PARS(PARS,IPAR)
C
C Add EXTI to PARS()
C
	REAL PARS(*)
C
	COMMON /EXTI_CORR_COM/ IEXTI_OPT,EXTI
C
	IPAR=IPAR+1
	PARS(IPAR)=EXTI
C
	RETURN
	END


	SUBROUTINE UNPACK_EXTI_PARS(IPAR, PARS,ESDS,LPRINT)
C
C Unpack EXTI from PARS() and optionally output the refined result
C
	LOGICAL LPRINT
	REAL PARS(*),ESDS(*)
C
	COMMON /EXTI_CORR_COM/ IEXTI_OPT,EXTI
C
	IPAR=IPAR+1
	EXTI=PARS(IPAR)
C
	IF(LPRINT) WRITE(10,'(/,A,F7.1,A,F6.1,A)')
	1		'Extinction parameter =',EXTI,' (',ESDS(IPAR),')'
C
	RETURN
	END
