C ----- Do the intensity correction for wav/2 contamination -------------------
c	SUBROUTINE HARMONIC_CORR
c	SUBROUTINE OUTPUT_HARM_COUNTS(ISEQ,COUNTS_SEQ2,ALPHA,ALPHA_ERR)
c	SUBROUTINE HARMONIC_CORR_INTS(NHKLS_1ESD,HARM_MAX,ISTATUS,
c	1								COUNTS_SEQ2,ALPHA,ALPHA_ERR,ISEQ)
c	SUBROUTINE FIT_HARM_INTS(ALPHA,ALPHA_ERR, COUNTS_SEQ2,ISEQ)
c	SUBROUTINE FIT_HARM_INTS2(ALPHA,ALPHA_ERR, COUNTS_SEQ2,ISEQ)
c	FUNCTION FIT_HARM_FUNC(COUNTS_SEQ2,ISEQ,ALPHA)
c	FUNCTION CALC_ICALC_WAV2(COUNTS_SEQ2,IREF)
c	SUBROUTINE CALC_Q_DISTRIB(COUNTS0,GRAD)
C -----------------------------------------------------------------------------


C ----- Do the intensity correction for wav/2 contamination -------------------

	SUBROUTINE HARMONIC_CORR
C
	PARAMETER (NDATA_MAX=2000000)
	INTEGER HKLMS(4,NDATA_MAX),IFILES(NDATA_MAX)
	REAL WAVS(NDATA_MAX),COUNTS(NDATA_MAX),DCOUNTS(NDATA_MAX)
	REAL TTHS(NDATA_MAX),XY_PIX(2,NDATA_MAX)
	COMMON /DATA_COM/ HKLMS,IFILES,WAVS,COUNTS,DCOUNTS,TTHS,XY_PIX,NDATA
C
	REAL ICALC,IOBS,ISIG
	COMMON /LSQ_FUNC_COM/ ICALC(NDATA_MAX),IOBS(NDATA_MAX),ISIG(NDATA_MAX)
C
	PARAMETER (NSEQ_MAX=100000)
	COMMON /SEQ_COM/ IFIRST(NSEQ_MAX),ILAST(NSEQ_MAX),COUNTS_SEQ(NSEQ_MAX),NSEQ
C
	COMMON /MISC_PARS_COM/ NSEQ_MIN,SEQ_FRAC,X_LO,X_HI,Y_LO,Y_HI,WAV_LO,WAV_HI,
	1	CELL_MULT,EFF_WIDTH,EFF_THICK,EXTI_CORR_MAX,NBINS_NPAR,
	2	ALL_REL_ERR,ALL_SIG_MULT,WEAK_SIG_MULT,EXTI_ERR,WAV_ERR1,WAV_ERR2,
	3	HARM_CUTOFF_MULT,IVERBOSE
C
	COMMON /HARM_INFO_COM/ HARM_MAX,NHKLS_1ESD
C
	REAL DCOUNTS_SEQ(NSEQ_MAX)
	REAL COUNTS_SEQ2(NSEQ_MAX),ALPHA(NSEQ_MAX),ALPHA_ERR(NSEQ_MAX)
C
C Write header to log file
C
	WRITE(10,'(/,A,/)') '====== Correction for harmonic (wav/2) contribution ======'
C
	IF(IVERBOSE .NE. 0) THEN
	  OPEN(UNIT=2,FILE='laue4_har.lis',STATUS='UNKNOWN')
	  WRITE(2,'(2A)') '   H   K   L    wav    Ints (',
	1					'   Old,          New,         Wav/2 )'
	ENDIF
C
C Calculate esd for DCOUNTS before we start playing with wav/2 intensities
C
	CALL CALC_ALL_DCOUNTS_SEQ(DCOUNTS_SEQ)
C
C Estimate parameters Y0 & GRAD where COUNTS_SEQ = Y0 * exp( -GRAD/d-space^2 )
C is a upper limit for observed intensities versus d-space
C
	CALL CALC_Q_DISTRIB(Y0,GRAD)
C
C Load COUNTS_SEQ2() the above estimated upper limits calculated for
C the wav/2 harmonic
C
	DO ISEQ=1,NSEQ
	  DSPACE=0.5 * WAVS(IFIRST(ISEQ)) / SIND( TTHS(IFIRST(ISEQ))/2.0 )
	  COUNTS_SEQ2(ISEQ)=Y0*EXP( -GRAD/(0.5*DSPACE)**2 ) 
	ENDDO
C
C Fit a sequence of counts for the wav/2 contribution using:
C 	IOBS (harm. corr.) = IOBS (raw) + ICALC2 * ALPHA
C where ALPHA is equal to the ratio of the harmonic intensity
C compared to the estimated maximum intensity for its Q value.
C
	DO ISEQ=1,NSEQ
C Set ALPHA_ERR < 0, to indicate failure
	  ALPHA_ERR(ISEQ)=-1.0
C Don't try to fit one member sequences
	  IF(ILAST(ISEQ) .EQ. IFIRST(ISEQ)) CYCLE
C Fit ALPHA to minimise SSQ (ALPHA_ERR<0 means failure)
	  CALL FIT_HARM_INTS(ALPHA(ISEQ),ALPHA_ERR(ISEQ), COUNTS_SEQ2(ISEQ),ISEQ)
C Set statistically insignificant ALPHA to ignore
	  IF(ALPHA(ISEQ) .LT. ALPHA_ERR(ISEQ)) ALPHA_ERR(ISEQ)=-1.0
	ENDDO
C
C Loop through reflections sequences correcting, or not, the intensities
C
	NSEQ_FIT=0
	NHKLS_1ESD=0
	HARM_MAX=-1E-6
	NSEQ_CORR=0
	DO ISEQ=1,NSEQ
	  IF(ALPHA_ERR(ISEQ) .LE. 0.0) CYCLE
C
	  NSEQ_FIT=NSEQ_FIT+1
	  CALL HARMONIC_CORR_INTS(NHKLS_1ESD,HARM_MAX,ISTATUS,
	1						COUNTS_SEQ2(ISEQ),ALPHA(ISEQ),ALPHA_ERR(ISEQ),ISEQ)
C 
	  IF(ISTATUS .EQ. 2) THEN
	    NSEQ_CORR=NSEQ_CORR+1
	    CALL OUTPUT_HARM_COUNTS(ISEQ,COUNTS_SEQ2(ISEQ),ALPHA(ISEQ),ALPHA_ERR(ISEQ))
	  ENDIF
	ENDDO
C
C Write summary of corrections to log file
C
	WRITE(10,'(A,F6.2,2(/,A))',IOSTAT=IDUM)
	1	'Alpha esd limit set by HARM_CUTOFF_MULT=',HARM_CUTOFF_MULT,
	2	'Limit increase linearly for d-space > 1',
	3	'   Alpha is the ratio of harmonic intensity to max. intensity estimate'
C
	WRITE(10,'(/,I6,A)') NSEQ-NSEQ_FIT,
	1	' equivalence groups with insignificant contamination'
	WRITE(10,'(I6,A)') NSEQ_FIT-NSEQ_CORR,
	1	' equivalence groups with alpha exceeding limit'
	WRITE(10,'(I6,A)') NSEQ_CORR,
	1	' equivalence groups corrected using linear regression'
	IF(NHKLS_1ESD .EQ. 0) THEN
	  WRITE(10,'(/,2A)') 'No significant harmonic contamination ',
	1			'detected, suggest disabling correction'
	ELSE
	  WRITE(10,'(I6,A,3X,A,F5.1,A)') NHKLS_1ESD,' hkls corrected by > 1 esd',
	1			'Max. correction =',MIN(999.9,HARM_MAX),' esds'
C
C Output the effect on the merge statistics to log file and console
C
	  PRINT '(/,1X,A)','Merge statistics after harmonic (wav/2) correction:'
	  CALL PRINT_LSQ_MERGE
	  WRITE(10,'(/,A)') 'Merge statistics after harmonic correction:'
	  CALL LOG_LSQ_MERGE
	ENDIF
C
	IF(IVERBOSE .NE. 0) THEN
	  WRITE(10,'(/,A)') 'Details of corrections written to "laue4_har.lis"'
	  CLOSE(UNIT=2)
	ENDIF
C
	RETURN
	END


	SUBROUTINE OUTPUT_HARM_COUNTS(ISEQ,COUNTS_SEQ2,ALPHA,ALPHA_ERR)
C
C
	PARAMETER (NDATA_MAX=2000000)
	INTEGER HKLMS(4,NDATA_MAX),IFILES(NDATA_MAX)
	REAL WAVS(NDATA_MAX),COUNTS(NDATA_MAX),DCOUNTS(NDATA_MAX)
	REAL TTHS(NDATA_MAX),XY_PIX(2,NDATA_MAX)
	COMMON /DATA_COM/ HKLMS,IFILES,WAVS,COUNTS,DCOUNTS,TTHS,XY_PIX,NDATA
C
	PARAMETER (NSEQ_MAX=100000)
	COMMON /SEQ_COM/ IFIRST(NSEQ_MAX),ILAST(NSEQ_MAX),COUNTS_SEQ(NSEQ_MAX),NSEQ
C
	COMMON /MISC_PARS_COM/ NSEQ_MIN,SEQ_FRAC,X_LO,X_HI,Y_LO,Y_HI,WAV_LO,WAV_HI,
	1	CELL_MULT,EFF_WIDTH,EFF_THICK,EXTI_CORR_MAX,NBINS_NPAR,
	2	ALL_REL_ERR,ALL_SIG_MULT,WEAK_SIG_MULT,EXTI_ERR,WAV_ERR1,WAV_ERR2,
	3	HARM_CUTOFF_MULT,IVERBOSE
C
	INTEGER HKL_EQV(3)
C
C Calculate harmonic intensity and extinction-free esd
C
	COUNTS2=COUNTS_SEQ2*ALPHA
	DCOUNTS2=COUNTS_SEQ2*ALPHA_ERR
C
C Get the worst extinction X value for harmonic sequence
C
	XMAX=0.0
	DO I=IFIRST(ISEQ),ILAST(ISEQ)
	  X=CALC_EXTI_FACTOR(COUNTS2,WAVS(I)/2.0,TTHS(I))
	  XMAX=MAX(XMAX,X)
	ENDDO
C
C Calculate extinction correction for XMAX, and its relative error
C
	Y=1.0/SQRT(1.0+XMAX)
	RERR=(1.0-Y)*EXTI_ERR
C
C Add extinction error, calculate "merge" hkl and output to log file
C
	DCOUNTS2=SQRT( DCOUNTS2**2 + (COUNTS2*RERR)**2 )
	CALL CALC_EQUIV_HKL(HKL_EQV, HKLMS(1,IFIRST(ISEQ)) )
	SCALE=10.0
	WRITE(10,'(3I4,2F8.1)') (2*HKL_EQV(K),K=1,3),SCALE*COUNTS2,SCALE*DCOUNTS2
C
	RETURN
	END


	SUBROUTINE HARMONIC_CORR_INTS(NHKLS_1ESD,HARM_MAX,ISTATUS,
	1								COUNTS_SEQ2,ALPHA,ALPHA_ERR,ISEQ)
C
	PARAMETER (NDATA_MAX=2000000)
	INTEGER HKLMS(4,NDATA_MAX),IFILES(NDATA_MAX)
	REAL WAVS(NDATA_MAX),COUNTS(NDATA_MAX),DCOUNTS(NDATA_MAX)
	REAL TTHS(NDATA_MAX),XY_PIX(2,NDATA_MAX)
	COMMON /DATA_COM/ HKLMS,IFILES,WAVS,COUNTS,DCOUNTS,TTHS,XY_PIX,NDATA
C
	REAL ICALC,IOBS,ISIG
	COMMON /LSQ_FUNC_COM/ ICALC(NDATA_MAX),IOBS(NDATA_MAX),ISIG(NDATA_MAX)
C
	COMMON /MISC_PARS_COM/ NSEQ_MIN,SEQ_FRAC,X_LO,X_HI,Y_LO,Y_HI,WAV_LO,WAV_HI,
	1	CELL_MULT,EFF_WIDTH,EFF_THICK,EXTI_CORR_MAX,NBINS_NPAR,
	2	ALL_REL_ERR,ALL_SIG_MULT,WEAK_SIG_MULT,EXTI_ERR,WAV_ERR1,WAV_ERR2,
	3	HARM_CUTOFF_MULT,IVERBOSE
C
	PARAMETER (NSEQ_MAX=100000)
	COMMON /SEQ_COM/ IFIRST(NSEQ_MAX),ILAST(NSEQ_MAX),COUNTS_SEQ(NSEQ_MAX),NSEQ
C
C Assume a 10% error in the intensity corrections
C
	ERR_FACTOR=0.1
C
C Calculate alpha cutoff which depends on d-spacing
C
	DSPACE=0.5* WAVS(IFIRST(ISEQ)) / SIND( 0.5*TTHS(IFIRST(ISEQ)) )
	CUTOFF=( 1.0 + MAX(0.0,2.0*(DSPACE-1.0)) )*HARM_CUTOFF_MULT
C
C In verbose mode, output the effect on individual intensities
C
	IF(IVERBOSE .NE. 0) THEN
	  WRITE(2,*)
	  DO I=IFIRST(ISEQ),ILAST(ISEQ)
C Calculate factor from observed counts to corrected intensities
	    CALL DERIV_COUNTS_SEQ(RFAC,DUMMY, COUNTS_SEQ(ISEQ),I)
	    RFAC=RFAC/COUNTS_SEQ(ISEQ)
	    ROBS=IOBS(I)/RFAC
	    RSIG=ISIG(I)/RFAC
	    RCALC2=CALC_ICALC_WAV2(ALPHA*COUNTS_SEQ2,I)/RFAC
	    RSIG2=SQRT( (ALPHA_ERR/ALPHA)**2 + ERR_FACTOR**2 )*RCALC2
	    RSIG_NEW=SQRT(RSIG**2 + RSIG2**2 )
	    WRITE(2,'(3I4,F8.3,3X,3(F8.1,1H(,F5.1,1H)))',IOSTAT=IDUM)
	1		(HKLMS(K,I),K=1,3),WAVS(I),ROBS,RSIG,
	2		ROBS-RCALC2,RSIG_NEW,RCALC2,RSIG2
	  ENDDO
C Output alpha and d-spacing of harmonic
	  WRITE(2,'(4X,2(A,F6.2),A,F6.2)',IOSTAT=IDUM)'Refined alpha =',
	1		ALPHA,'(',ALPHA_ERR,')  for harmonic d-spacing =',DSPACE/2.0
	ENDIF
C
C If alpha greater than cutoff, reject correction and return
C
	IF(ALPHA_ERR .GT. CUTOFF) THEN
	  IF(IVERBOSE .NE. 0) WRITE(2,'(4X,A,F6.2)',IOSTAT=IDUM)
	1			'Correction rejected: Alpha esd >',CUTOFF
	  ISTATUS=1
	  RETURN
	ENDIF
C
C Save for verbose output the original COUNTS_SEQ and esd
C
	COUNTS_SAVE=COUNTS_SEQ(ISEQ)
	DCOUNTS_SAVE=CALC_DCOUNTS_SEQ(ISEQ)
C
C Correct IOBS & ISIG, and collect some statistics
C
	DO I=IFIRST(ISEQ),ILAST(ISEQ)
	  CALC2=CALC_ICALC_WAV2(ALPHA*COUNTS_SEQ2,I)
	  IOBS(I)=IOBS(I)-CALC2
	  SIG2=SQRT( (ALPHA_ERR/ALPHA)**2 + ERR_FACTOR**2 )*CALC2
	  ISIG(I)=SQRT( ISIG(I)**2 + SIG2**2 )
	  HARM_MAX=MAX(HARM_MAX, CALC2/ISIG(I) )
	  IF(CALC2 .GE. ISIG(I)) NHKLS_1ESD=NHKLS_1ESD+1
	ENDDO
C
C Recalculate COUNTS_SEQ and esd (and ICALC)
C
	COUNTS_SEQ(ISEQ)=CALC_COUNTS_SEQ(COUNTS_SEQ(ISEQ), IFIRST(ISEQ),ILAST(ISEQ))
	DCOUNTS_SEQ=CALC_DCOUNTS_SEQ(ISEQ)
C
C In verbose mode, output the effect on merged intensities
C
	IF(IVERBOSE .NE. 0) THEN
	  WRITE(2,'(4X,2(A,F8.1,A,F5.1),A)',IOSTAT=IDUM)
	1		'Merged results',COUNTS_SAVE,'(',DCOUNTS_SAVE,')  >>',
	2		COUNTS_SEQ(ISEQ),'(',DCOUNTS_SEQ,')'
	ENDIF
C
	ISTATUS=2
	RETURN
	END


	SUBROUTINE FIT_HARM_INTS(ALPHA,ALPHA_ERR, COUNTS_SEQ2,ISEQ)
C
C Calculates ALPHA, and its esd ALPHA_ERR, for the minimum merge SSQ
C intensities in sequence ISEQ. In this case, the merge intensities
C are the "normal" intensities with harmonic intensity subtracted.
C Returns ALPHA=0 if algorithm fails.
C
C
	PARAMETER (NSEQ_MAX=100000)
	COMMON /SEQ_COM/ IFIRST(NSEQ_MAX),ILAST(NSEQ_MAX),COUNTS_SEQ(NSEQ_MAX),NSEQ
C
	PARAMETER (NDATA_MAX=2000000)
	REAL ICALC,IOBS,ISIG
	COMMON /LSQ_FUNC_COM/ ICALC(NDATA_MAX),IOBS(NDATA_MAX),ISIG(NDATA_MAX)
C
C Simple iterative search for minimum SSQ versus ALPHA
C Covers ALPHA=0.001 to 1000 to within 1% accuracy
C
	SSQ_MIN=1E10
	RMULT=10.0
	X0=1.0
	DO I=-3,3
	  X=X0*RMULT**I
	  SSQ=FIT_HARM_FUNC(COUNTS_SEQ2,ISEQ,X)
	  IF(SSQ .LT. SSQ_MIN) THEN
	    XMIN=X
	    SSQ_MIN=SSQ
	  ENDIF
	ENDDO
	X0=XMIN
C
	DO ITER=1,8
C
	  RMULT=SQRT(RMULT)
	  SSQ1=FIT_HARM_FUNC(COUNTS_SEQ2,ISEQ,X0/RMULT)
	  SSQ2=SSQ_MIN
	  SSQ3=FIT_HARM_FUNC(COUNTS_SEQ2,ISEQ,X0*RMULT)
	  IF(SSQ1 .LT. SSQ3) THEN
	    IF(SSQ1 .LT. SSQ2) THEN
	      X0=X0/RMULT
	      SSQ_MIN=SSQ1
	    ENDIF
	  ELSE
	    IF(SSQ3 .LT. SSQ2) THEN
	      X0=X0*RMULT
	      SSQ_MIN=SSQ3
	    ENDIF
	  ENDIF
	  X=X0*RMULT
C
	ENDDO
C
C Calculate curvature of solution, fail if negative
C
	QUAD=0.5*(SSQ1+SSQ3)-SSQ2
	IF(QUAD .LE. 0.0) THEN
	  ALPHA=0.0
	  RETURN
	ENDIF
C
C Return ALPHA and its esd
C
	ALPHA=X0
	DX=X0*(RMULT-1.0)
	ALPHA_ERR=DX/SQRT(QUAD)
C
	RETURN
	END



	SUBROUTINE FIT_HARM_INTS2(ALPHA,ALPHA_ERR, COUNTS_SEQ2,ISEQ)
C
C Calculates ALPHA, and its esd ALPHA_ERR, for the minimum merge SSQ
C intensities in sequence ISEQ. In this case, the observed intensities
C are the "normal" intensities with ALPHA*ICALC2() subtracted.
C Returns ALPHA=0 if algorithm fails.
C
C
	PARAMETER (NSEQ_MAX=100000)
	COMMON /SEQ_COM/ IFIRST(NSEQ_MAX),ILAST(NSEQ_MAX),COUNTS_SEQ(NSEQ_MAX),NSEQ
C
	PARAMETER (NDATA_MAX=2000000)
	REAL ICALC,IOBS,ISIG
	COMMON /LSQ_FUNC_COM/ ICALC(NDATA_MAX),IOBS(NDATA_MAX),ISIG(NDATA_MAX)
C
C Set ALPHA=0 in case of failure
C
	ALPHA=0.0
C
C Calculate SSQ for ALPHA={0.1,1,10} and substract off the SSQ for ALPHA=0
C
	SSQ0=FIT_HARM_FUNC(COUNTS_SEQ2,ISEQ,0.0)
	SSQ1=FIT_HARM_FUNC(COUNTS_SEQ2,ISEQ,0.1)   -SSQ0
	SSQ2=FIT_HARM_FUNC(COUNTS_SEQ2,ISEQ,1.0)   -SSQ0
	SSQ3=FIT_HARM_FUNC(COUNTS_SEQ2,ISEQ,10.0)  -SSQ0
C
C Cubic fit of SSQ ~ A1*ALPHA^1 + A2*ALPHA^2 + A3*ALPHA^3
C
	A1= 11.22334456*SSQ1 -0.12345679*SSQ2 +0.000112233*SSQ3
	A2=-12.34567901*SSQ1 +1.24691358*SSQ2 -0.001234568*SSQ3
	A3= 1.122334456*SSQ1 -0.12345679*SSQ2 +0.001122334*SSQ3
C
C Return with ALPHA=0 if gradient at zero is non-negative
C
	IF(A1 .GE. 0) RETURN
C
C Calculate the position of the cubic local minimum, XMIN
C If no local minimum, return with ALPHA=0
C
	ROOT=A2*A2-3.0*A1*A3
	IF(ROOT .LE. 0.0) RETURN
	XMIN=-A2/(3.0*A3) +SQRT(ROOT)/(3.0*A3)
C
C If ridiculous XMIN values, return with ALPHA=0
C
	IF(XMIN.LE.0.0 .OR. XMIN.GE.1E3) RETURN
C
C Quadratic interpolation of SSQ at ALPHA = XMIN*{0.5,1.0,1.5}
C
	SSQ05=FIT_HARM_FUNC(COUNTS_SEQ2,ISEQ,XMIN*0.5)
	SSQ10=FIT_HARM_FUNC(COUNTS_SEQ2,ISEQ,XMIN)
	SSQ15=FIT_HARM_FUNC(COUNTS_SEQ2,ISEQ,XMIN*1.5)
C
C Check for "impossible" values, giveup if we find any
C
	DENOM=0.5*(SSQ05+SSQ15)-SSQ10
	IF(DENOM.LE.0.0 .OR. SSQ10.GE.SSQ05) RETURN
C
C Calculate ALPHA & ALPHA_ERR at quadratic minimum and return
C
	ALPHA=XMIN*(1.0+0.125*(SSQ05-SSQ15)/DENOM)
	ALPHA_ERR=0.5*XMIN/SQRT(DENOM)
C
	RETURN
	END


	FUNCTION FIT_HARM_FUNC(COUNTS_SEQ2,ISEQ,ALPHA)
C
	PARAMETER (NSEQ_MAX=100000)
	COMMON /SEQ_COM/ IFIRST(NSEQ_MAX),ILAST(NSEQ_MAX),COUNTS_SEQ(NSEQ_MAX),NSEQ
C
	PARAMETER (NDATA_MAX=2000000)
	REAL ICALC,IOBS,ISIG
	COMMON /LSQ_FUNC_COM/ ICALC(NDATA_MAX),IOBS(NDATA_MAX),ISIG(NDATA_MAX)
C
	REAL ISAVE(NDATA_MAX)
C
C Save the IOBS for this sequence
C
	DO I=IFIRST(ISEQ),ILAST(ISEQ)
	  ISAVE(I)=IOBS(I)
	ENDDO
C
C Subtract ALPHA*ICALC2 from IOBS
C
	DO I=IFIRST(ISEQ),ILAST(ISEQ)
	  IOBS(I)=IOBS(I)-CALC_ICALC_WAV2(ALPHA*COUNTS_SEQ2,I)
	ENDDO
C
C Calculate a new COUNTS_SEQ for these IOBS
C
	DUMMY=CALC_COUNTS_SEQ(COUNTS_SEQ(ISEQ), IFIRST(ISEQ),ILAST(ISEQ))
C
C Calculate SSQ of IOBS - ICALC using the new COUNTS_SEQ
C
	SSQ=0.0
	DO I=IFIRST(ISEQ),ILAST(ISEQ)
	  SSQ=SSQ + ( (ICALC(I)-IOBS(I))/ISIG(I) )**2
	ENDDO
C
C Restore the IOBS for this sequence
C
	DO I=IFIRST(ISEQ),ILAST(ISEQ)
	  IOBS(I)=ISAVE(I)
	ENDDO
C
C Restore ICALC for the sequence (don't need to recalculate COUNTS_SEQ)
C
	DUMMY=CALC_COUNTS_SEQ(COUNTS_SEQ(ISEQ), IFIRST(ISEQ),ILAST(ISEQ))
C
	FIT_HARM_FUNC=SSQ
	RETURN
	END


	FUNCTION CALC_ICALC_WAV2(COUNTS_SEQ2,IREF)
C
C Returns the calculated intensity for each reflection as if measured
C at WAV/2 instead of WAV and using COUNTS_SEQ2() instead of COUNTS_SEQ().
C
	PARAMETER (NDATA_MAX=2000000)
	INTEGER HKLMS(4,NDATA_MAX),IFILES(NDATA_MAX)
	REAL WAVS(NDATA_MAX),COUNTS(NDATA_MAX),DCOUNTS(NDATA_MAX)
	REAL TTHS(NDATA_MAX),XY_PIX(2,NDATA_MAX)
	COMMON /DATA_COM/ HKLMS,IFILES,WAVS,COUNTS,DCOUNTS,TTHS,XY_PIX,NDATA
C
C Calculate intensities for wav/2 harmonic
C
	WAVS(IREF)=WAVS(IREF)*0.5
	CALL DERIV_COUNTS_SEQ(CALC2,DUMMY, COUNTS_SEQ2,IREF)
	WAVS(IREF)=WAVS(IREF)*2.0
C
C If CALC_WAV_ROUGH=1E-6, then CALC2 is really zero
C
	IF(CALC_WAV_ROUGH(WAVS(IREF)) .LT. 1.1E-6) CALC2=0.0
C
	CALC_ICALC_WAV2=CALC2
	RETURN
	END


	SUBROUTINE CALC_Q_DISTRIB(COUNTS0,GRAD)
C
C Fit COUNTS_SEQ to COUNTS0 * exp( -GRAD/d-space^2 )
C
	PARAMETER (NDATA_MAX=2000000)
	INTEGER HKLMS(4,NDATA_MAX),IFILES(NDATA_MAX)
	REAL WAVS(NDATA_MAX),COUNTS(NDATA_MAX),DCOUNTS(NDATA_MAX)
	REAL TTHS(NDATA_MAX),XY_PIX(2,NDATA_MAX)
	COMMON /DATA_COM/ HKLMS,IFILES,WAVS,COUNTS,DCOUNTS,TTHS,XY_PIX,NDATA
C
	PARAMETER (NSEQ_MAX=100000)
	COMMON /SEQ_COM/ IFIRST(NSEQ_MAX),ILAST(NSEQ_MAX),COUNTS_SEQ(NSEQ_MAX),NSEQ
C
C Get three largest "accurate" COUNTS_SEQ values
C
	CMAX1=-1.0
	CMAX2=-2.0
	CMAX3=-3.0
	DO I=1,NSEQ
	  DCOUNTS_SEQ=CALC_DCOUNTS_SEQ(I)
	  IF(COUNTS_SEQ(I) .LT. 10.0*DCOUNTS_SEQ) CYCLE
	  IF(COUNTS_SEQ(I) .LT. CMAX3) CYCLE
C
	  IF(COUNTS_SEQ(I) .GT. CMAX1) THEN
	    CMAX3=CMAX2
	    CMAX2=CMAX1
	    CMAX1=COUNTS_SEQ(I)
	  ELSEIF(COUNTS_SEQ(I) .GT. CMAX2) THEN
	    CMAX3=CMAX2
	    CMAX2=COUNTS_SEQ(I)
	  ELSE
	    CMAX2=COUNTS_SEQ(I)
	  ENDIF
	ENDDO
C
C Use third largest for Y0 (in case first 2 are anomalies)
C
	COUNTS0=CMAX3
C
C Ignore data and set Uiso = 0.02 A-2
C
	GRAD=4.0/3.0*3.1416**2 * 0.02
C
	WRITE(10,'(A)') 'Assumed intensity distribution versus d-spacing'
	WRITE(10,'(5X,9F6.2)') (SQRT(0.5)**K,K=-4,4)
	WRITE(10,'(5X,9I6)') (NINT(  1E3*EXP(-GRAD*(2.0**K))  ),K=-4,4)
C
	RETURN
	END
