	SUBROUTINE GENERATE_HKL_VECTORS(B)
C
C Generate a list of unit scattering vectors H_HKLS(3,1..NHKLS)
C for all reflections generated by MAKE_HKL_LIST
C
	REAL B(3,3)
C
	PARAMETER (NHKLS_MAX=1000)
	COMMON /HKL_VECTORS_COM/ NHKLS,H_HKLS(3,NHKLS_MAX)
C
	INTEGER IHKLS(3,NHKLS_MAX)
	REAL RHKL(3)
C
	CALL MAKE_HKL_LIST(IHKLS,NHKLS)
C
	DO I=1,NHKLS
	  CALL VC3_SET(RHKL, FLOAT(IHKLS(1,I)),FLOAT(IHKLS(2,I)),FLOAT(IHKLS(3,I)))
	  CALL VC3_MULT(H_HKLS(1,I), B,RHKL)
	  CALL VC3_UNIT(H_HKLS(1,I))
	ENDDO
C
	PRINT '(1X,I7,A)',NHKLS,' low indices HKLs generated'
	RETURN
	END



	SUBROUTINE MAKE_HKL_LIST(IHKL,NUM_HKL)
C
C Create a list of H,K,L with H*H+K*K+L*L <= IHSQ_MAX and
C without common factors such as 246 or 369. Also exclude 000.
C
	COMMON /HKLGEN_COM/ IHSQ_MAX
C
	PARAMETER (NHKLS_MAX=1000)
	INTEGER IHKL(3,NHKLS_MAX)
C
	LOGICAL CHECK_COFACTORS3
C
	IF(IHSQ_MAX .GT. 24) CALL QUIT('BUG(make_hkl_list) IHSQ_MAX > 24')
C
C Loop through H,K,L from -NMAX to +NMAX
C
	N=0
	NMAX=INT(SQRT(IHSQ_MAX+0.1))
	DO I1=-NMAX,NMAX
	  DO I2=-NMAX,NMAX
	    DO I3=-NMAX,NMAX
C Ignore if outside the IHKL2_GEN_MAX limit
	      IF(I1*I1+I2*I2+I3*I3 .GT. IHSQ_MAX) THEN
C Ignore this HKL if 0,0,0 or it has common factors
	      ELSE IF(I1.EQ.0 .AND. I2.EQ.0 .AND. I3.EQ.0) THEN
	      ELSE IF( CHECK_COFACTORS3(I1,I2,I3) ) THEN
	      ELSE
C HKL is OK, so add it to the list
	        N=N+1
	        IF(N .GT. NHKLS_MAX) CALL QUIT('BUG(make_hkl_list): N too big')
	        IHKL(1,N)=I1
	        IHKL(2,N)=I2
	        IHKL(3,N)=I3
	      ENDIF
C
	    ENDDO
	  ENDDO
	ENDDO
C
C Return the total number of HKLs generated
C
	NUM_HKL=N
C
	RETURN
	END



	LOGICAL FUNCTION CHECK_COFACTORS3(I1,I2,I3)
C
C Return TRUE if I1, I2, I3 have a common factor
C
	INTEGER PRIMES(15)
	DATA PRIMES/2,3,5,7,11,13,17,19,23,29,31,37,41,43,51/
C
C Loop through primes up to 51
C
	DO I=1,15
	  IP=PRIMES(I)
	  I1R=I1/IP
	  I2R=I2/IP
	  I3R=I3/IP
C If I1, I2 & I3 are divisible by the prime, return TRUE
C	PRINT *,I1,I2,I3,IP,I1R*IP,I2R*IP,I3R*IP
	  IF(I1R*IP.EQ.I1 .AND. I2R*IP.EQ.I2 .AND. I3R*IP.EQ.I3) THEN
	    CHECK_COFACTORS3=.TRUE.
	    RETURN
	  ELSE
C Stop if the prime is larger than I1, I2 OR I3, so return FALSE
	    IF(IP .GE. MAX(ABS(I1),ABS(I2),ABS(I3))) THEN
	      CHECK_COFACTORS3=.FALSE.
	      RETURN
	    ENDIF
	  ENDIF
	ENDDO
C Sanity check
	CALL QUIT('BUG(check_cofactors3): Primes list exceeded')
	END



	SUBROUTINE MAKE_HKL_ANGLES_TABLE
C
C Create a sorted table of the angles between all hkl vectors, H_HKL().
C The angles are stored in ANGLES(), the two hkls are indexed by IANGLES(),
C and ITAGS() contain the index to ANGLES() & IANGLES() in sorted order.
C
C
	EXTERNAL PAIR_ANGLE_COMPARE
C
	PARAMETER (NHKLS_MAX=1000)
	COMMON /HKL_VECTORS_COM/ NHKLS,H_HKLS(3,NHKLS_MAX)
C
	PARAMETER (NANGLES_MAX=150000)
	COMMON /ANGLES_COM/ NANGLES,ANGLES(NANGLES_MAX),IANGLES(2,NANGLES_MAX)
C
	INTEGER ITAGS(NANGLES_MAX),ITEMP(2,NANGLES_MAX)
	REAL TEMP(NANGLES_MAX)
C
	NANGLES=0
	DO I1=1,NHKLS
	  DO I2=1,I1-1
	    DOT=VC3_DOT(H_HKLS(1,I1),H_HKLS(1,I2))
	    IF(ABS(DOT) .GT. 1.0+1E-6) CALL QUIT('BUG: DOT > 1')
	    ANGLE=ACOSD( MAX(-1.0,MIN(1.0, DOT )) )
	    NANGLES=NANGLES+1
	    IF(NANGLES .GT. NANGLES_MAX)
	1				CALL QUIT('BUG(make_hkl_angles_table): Too many angles')
	    ANGLES(NANGLES)=ANGLE
	    IANGLES(1,NANGLES)=I1
	    IANGLES(2,NANGLES)=I2
	    NANGLES=NANGLES+1
	    ANGLES(NANGLES)=ANGLE
	    IANGLES(1,NANGLES)=I2
	    IANGLES(2,NANGLES)=I1
	  ENDDO
	ENDDO
C
	PRINT '(1X,I7,A)',NANGLES,' angles calculated between HKLs'
C
C Do a tagged sort on the ANGLES()
C
	CALL TAG_SORT(PAIR_ANGLE_COMPARE,ITAGS,NANGLES)
C
C Sort the ANGLES() & IANGLES() arrays using the tags
C
	DO I1=1,NANGLES
	  I2=ITAGS(I1)
	  TEMP(I1)=ANGLES(I2)
	  ITEMP(1,I1)=IANGLES(1,I2)
	  ITEMP(2,I1)=IANGLES(2,I2)
	ENDDO
C
	DO I=1,NANGLES
	  ANGLES(I)=TEMP(I)
	  IANGLES(1,I)=ITEMP(1,I)
	  IANGLES(2,I)=ITEMP(2,I)
	  ITAGS(I)=I
	ENDDO
C
	RETURN
	END



	SUBROUTINE FIND_ANGLES(I1,I2, ANGLE0,DANGLE)
C
C Find I1,I2, such that ANGLES(ITAGS(I1)) is just larger than (or equal to)
C ANGLE1 and ANGLES(ITAGS(I2)) is just smaller than (or equal to) ANGLE2
C
	PARAMETER (NANGLES_MAX=150000)
	COMMON /ANGLES_COM/ NANGLES,ANGLES(NANGLES_MAX),IANGLES(2,NANGLES_MAX)
C
	ANGLE1=ANGLE0-ABS(DANGLE)
	ANGLE2=ANGLE0+ABS(DANGLE)
C
	IFIRST=1
	ILAST=NANGLES
C
100	ITRY=(IFIRST+ILAST)/2
	ANGLE=ANGLES(ITRY)
	IF(ANGLE .LT. ANGLE1) THEN
	  IFIRST=ITRY
	ELSE IF(ANGLE .GT. ANGLE2) THEN
	  ILAST=ITRY
	ELSE
	  GOTO 200
	ENDIF
	IF(ILAST-IFIRST .GT. 1) GOTO 100
C
C No angles within the range so return zeroes to indicate failure
C
	I1=0
	I2=0
	RETURN
C
C At least one occurence within range, now try to find others
C
200	I1=ITRY
	I2=I1
C
C Search for limits of I1 & I2 using steps of 64 then 8 then 1
C
	NSTEP=64
	DO ISTEP=1,3
C
	  DO ITRY=I1-1,1,-NSTEP
	    IF(ANGLES(ITRY) .LT. ANGLE1) EXIT
	  ENDDO
	  I1=ITRY+NSTEP
C
	  DO ITRY=I2+1,NANGLES,NSTEP
	    IF(ANGLES(ITRY) .GT. ANGLE2) EXIT
	  ENDDO
	  I2=ITRY-NSTEP
C
	  NSTEP=NSTEP/8
	ENDDO
C
	RETURN
	END
