	SUBROUTINE WRITE_IMAGE_OLD(FILE_NAME,ICOMPRESS)
C
C Unused function that wrote a 'compressed' size image
C
	CHARACTER FILE_NAME*(*)
C
	INTEGER*2 IMAGE2(20000000)
	COMMON /IMAGE2_COM/ IMAGE2,NUMX,NUMY
C
	INTEGER*2 IMAGE2_OUT(1000000)
C
	PRINT '(1X,A,I2,2A)','Writing',ICOMPRESS,':1 compressed image to ',TRIM(FILE_NAME)
	IF(NUMX*NUMY/ICOMPRESS/ICOMPRESS .GT. 1000000)CALL QUIT('ERROR: Compressed image too big')
C
	IOUT=0
	DO IY=1,NUMY/ICOMPRESS
	  DO IX=1,NUMX/ICOMPRESS
	    SUM=0.0
	    DO IX2=IX*ICOMPRESS,(IX+1)*ICOMPRESS-1
	      DO IY2=IY*ICOMPRESS,(IY+1)*ICOMPRESS-1
	        SUM=SUM+COUNTS(IX2,IY2)
	      ENDDO
	    ENDDO
	    ISUM=NINT(SUM/ICOMPRESS/ICOMPRESS)
	    IF(ISUM .GE. 128*256) ISUM=ISUM-256*256
	    IOUT=IOUT+1
	    IMAGE2_OUT(IOUT)=ISUM
	  ENDDO
	ENDDO
C
	CALL WRITE_I2_FILE(FILE_NAME,IMAGE2_OUT,IOUT)
C
	RETURN
	END


	SUBROUTINE WRITE_I2_FILE(FILE_NAME,I2_OUT,NOUT)
C
	CHARACTER FILE_NAME*(*)
	INTEGER*2 I2_OUT(NOUT)
C
	OPEN(UNIT=2,FILE=FILE_NAME,STATUS='UNKNOWN',FORM='BINARY',
	1					ACCESS='SEQUENTIAL')
	WRITE(2) I2_OUT
	CLOSE(UNIT=2)
C
	RETURN
	END


	SUBROUTINE READ_IMAGE(FILE_NAME)
C
	CHARACTER FILE_NAME*(*)
C
	CHARACTER*2000 COMMENT,SAMPLE,USER,DATETIME,HOST,BEAM,ADC_INFO
	COMMON /TIFFINFO_COM/ COMMENT,SAMPLE,USER,DATETIME,HOST,BEAM,
	1			IOFF_DATA,NUMX,NUMY,IXYRES,ISTARTX,ISTARTY,ISPEED,
	2			EXPOSE_TIME,EXPOSE_PHI,TEMP_BEGIN,TEMP_END,TEMP_MIN,TEMP_MAX,
	3			IADC,ADC_ADD,ADC_DIV,ADC_INFO,IAPER_1,IAPER_2,IKAPPA
C
	INTEGER*2 IMAGE2(20000000)
	COMMON /IMAGE2_COM/ IMAGE2,NUMX2,NUMY2
C
	PRINT '(/,1X,2A)','Reading data file: ',FILE_NAME
C
	CALL CHECK_LAUE_TIFF(NUMX,NUMY, FILE_NAME)
	IF(NUMX*NUMY .GT. 20000000) CALL QUIT('ERROR: Image too large (> 20M pixels)')
	IF(NUMX .LT. 0) CALL QUIT('ERROR: TIF file header is invalid')
C
	NUMX2=NUMX
	NUMY2=NUMY
C
	CALL READ_LAUE_TIFF(IMAGE2,NUMX,NUMY, FILE_NAME)
C
	RETURN
	END



	SUBROUTINE GET_NUM_XY(NUMX0,NUMY0)
C
	INTEGER*2 IMAGE2(20000000)
	COMMON /IMAGE2_COM/ IMAGE2,NUMX,NUMY
C
	NUMX0=NUMX
	NUMY0=NUMY
C
	RETURN
	END



	FUNCTION COUNTS(IX,IY)
C
	INTEGER*2 IMAGE2(20000000)
	COMMON /IMAGE2_COM/ IMAGE2,NUMX,NUMY

C
	IF(IX.GE.1 .AND. IX.LE.NUMX .AND. IY.GE.1 .AND. IY.LE.NUMY) THEN
	  COUNTS=ZEXT( IMAGE2( IX+(IY-1)*NUMX ) )
	ELSE
	  COUNTS=0.0
	ENDIF
C
	RETURN
	END
