	SUBROUTINE READ_PAR_FILE(UB1,UB2,MAX_HKL,WAV_MIN,DXY_MAX,NITER,LFITCELL,FILE_NAME)
C
	LOGICAL LFITCELL
	CHARACTER FILE_NAME*(*)
	REAL UB1(3,3),UB2(3,3)
C
	COMMON /CELL_COM/ CELL(6),ILATT,ICEN
C
	COMMON /PIXEL_COM/ PIX_CEN(2),PIX_SIZE(2),PIX_SKEW
	COMMON /OFFSETS_COM/ XTAL_OFF(3),DRUM_OFF(3),BEAM_VERT
	COMMON /GEOM_COM/ ITYPE,NUMX,NUMY,DRUM_RAD,PHI
C
	OPEN(UNIT=1,FILE='___laueg_orient_twins.in',STATUS='OLD',ERR=900)
C
C Name of TIF file
C
	READ(1,'(A)',ERR=901) FILE_NAME
C
C Parameters for hkl generatoin
C
	READ(1,*,ERR=901) MAX_HKL,WAV_MIN,DXY_MAX,NITER
C
C Fit all cell dimensions, or don't change
C
	READ(1,*,ERR=900) IFITCELL
	LFITCELL=(IFITCELL .EQ. 1)
C
C Geometry parameters
C
C Input instrument type
	READ(1,*,ERR=901) ITYPE
C Input common lattice and cell info
	READ(1,*,ERR=901) ILATT,ICEN
	READ(1,*,ERR=901) CELL
C Input UB for Twin 1
	READ(1,*,ERR=901) (UB1(1,K),K=1,3)
	READ(1,*,ERR=901) (UB1(2,K),K=1,3)
	READ(1,*,ERR=901) (UB1(3,K),K=1,3)
C Input UB for Twin 2
	READ(1,*,ERR=901) (UB2(1,K),K=1,3)
	READ(1,*,ERR=901) (UB2(2,K),K=1,3)
	READ(1,*,ERR=901) (UB2(3,K),K=1,3)
C Input info probably used by all instruments
	READ(1,*,ERR=901) PHI
	READ(1,*,ERR=901) NUMX,NUMY
	READ(1,*,ERR=901) PIX_CEN
	READ(1,*,ERR=901) XTAL_OFF
	READ(1,*,ERR=901) DRUM_OFF
	READ(1,*,ERR=901) BEAM_VERT
C Input info that may vary for instruments
	READ(1,*,ERR=901) PIX_SIZE,PIX_SKEW
	READ(1,*,ERR=901) DRUM_RAD
C
	CLOSE(UNIT=1)
C
C For orienting spots, rhom(hex) & hex are the same
C NB: R centering is handled by ICEN not ILATT
C
	IF(ILATT .EQ. 8) ILATT=7
C
	RETURN
C
900	CALL QUIT('ERROR: Unable to open input file')
901	CALL QUIT('ERROR: Unable to read input file')
	END


	SUBROUTINE LOAD_STRIPPED_IMAGE(FILE_NAME)
C
	CHARACTER FILE_NAME*(*)
C
	COMMON /PIXEL_COM/ PIX_CEN(2),PIX_SIZE(2),PIX_SKEW
	COMMON /GEOM_COM/ ITYPE,NUMX,NUMY,DRUM_RAD,PHI
C
	COMMON /BACK_GEOM_COM/ NUMX2,NUMY2,IXCEN2,IYCEN2,XSIZE2,YSIZE2,DRUM_RAD2,IPIXCEN2
C
	PARAMETER (MAX_NUMX=8000,MAX_NUMY=2500)
	COMMON /RIMAGE_COM/ RIMAGE(MAX_NUMX,MAX_NUMY),NUMX3,NUMY3
C
	INTEGER*2 IMAGE2_READ(MAX_NUMX*MAX_NUMY)
	REAL BACK(MAX_NUMX,MAX_NUMY)
C
C Read the image data into /RIMAGE_COM/
C
	PRINT '(/,1X,2A)','Reading data file: ',FILE_NAME
C
C Read the TIF file
C
	CALL READ_LAUE_TIFF(IMAGE2_READ,NUMX,NUMY, FILE_NAME)
C
C Convert to REAL intensities and copy to /RIMAGE_COM/
C
	DO IY=1,NUMY
		DO IX=1,NUMX
			RIMAGE(IX,IY)=ZEXT( IMAGE2_READ( IX+(IY-1)*NUMX ) )
		ENDDO
	ENDDO
C
C Get central hole and base intensity from the image data
C
	IXHOLE=PIX_CEN(1)
	IYHOLE=PIX_CEN(2)
	IRAD=50
	CALL FIT_HOLE_APPROX(IXHOLE,IYHOLE, IRAD,NUMX/8,NUMY/8)
C
C Strip base-counts from intensities
C
	CALL GET_BASE_COUNTS(IBASE, IXHOLE,IYHOLE,IRAD)
	DO IY=1,NUMY
		DO IX=1,NUMX
			RIMAGE(IX,IY)=MAX(1.0, RIMAGE(IX,IY)-IBASE )
		ENDDO
	ENDDO
C
C Exclude pixels in central hole and borders of IP
C
	CALL SET_EXCLUDES(IXHOLE,IYHOLE,IRAD,NUMX,NUMY)
C
C Copy parameters from /PIXEL_COM/ & /GEOM_COM/ to /BACK_GEOM_COM/ & /RIMAGE_COM/
C
	NUMX2=NUMX
	NUMY2=NUMY
	NUMX3=NUMX
	NUMY3=NUMY
	IXCEN2=NINT(PIX_CEN(1))
	IYCEN2=NINT(PIX_CEN(2))
	XSIZE2=PIX_SIZE(2)
	YSIZE2=PIX_SIZE(2)
	DRUM_RAD2=DRUM_RAD
	IPIXCEN2=0
C
C Extract the background component from image values
C
	CALL CALC_BACK_ARRAY(BACK, RIMAGE)
C
C Subtract background from image
C
	DO IY=1,NUMY
	  DO IX=1,NUMX
	    RIMAGE(IX,IY)=RIMAGE(IX,IY)-BACK(IX,IY)
	  ENDDO
	ENDDO
C
	RETURN
	END


	SUBROUTINE SET_EXCLUDES(IXHOLE,IYHOLE,IRAD,NUMX,NUMY)
C
	COMMON /EXCLUDE_COM/ NCIRC,ICIRC(3,999),NRECT,IRECT(4,999)
C
C Use central hole as the only exclusion circle
C
	NCIRC=1
	ICIRC(1,1)=IXHOLE
	ICIRC(2,1)=IYHOLE
	ICIRC(3,1)=IRAD
C
C Set four exclusion rectangles for 40 pixel wide IP borders
C
	IBORD=40
C
	IRECT(1,1)=1
	IRECT(2,1)=NUMX
	IRECT(3,1)=1
	IRECT(4,1)=IBORD
C
	IRECT(1,2)=1
	IRECT(2,2)=NUMX
	IRECT(3,2)=NUMY-IBORD+1
	IRECT(4,2)=NUMY
C
	IRECT(1,3)=1
	IRECT(2,3)=IBORD
	IRECT(3,3)=1
	IRECT(4,3)=NUMY
C
	IRECT(1,4)=NUMX-IBORD+1
	IRECT(2,4)=NUMX
	IRECT(3,4)=1
	IRECT(4,4)=NUMY
C
	NRECT=4
C
	RETURN
	END


      SUBROUTINE FIT_HOLE_APPROX(IXCEN,IYCEN, IRCEN,IDX,IDY)
C
C Find approximate hole center in image at IXCEN+/-IDX, IYCEN+/-IDY using
C an approximate radius of IRCEN.
C New hole center is returned in IXCEN,IYCEN.
C
	PARAMETER (MAX_NUMX=8000,MAX_NUMY=2500,IUNIT=6)
	COMMON /RIMAGE_COM/ RIMAGE(MAX_NUMX,MAX_NUMY),NUMX,NUMY
C
      BEST=1E9
      DO IX=IXCEN-IDX,IXCEN+IDX
	  DO IY=IYCEN-IDY,IYCEN+IDY
          VAL=RIMAGE(IX,IY)*(IRCEN+ABS(IX-IXCEN)+ABS(IY-IYCEN))
          IF(VAL .LT. BEST) THEN
            BEST=VAL
            IXCEN2=IX
            IYCEN2=IY
          ENDIF
        ENDDO
      ENDDO
      IF(BEST .GT. 0.9E9) STOP 'BUG: fit_hole_approx #1'
C
      IXCEN=IXCEN2
      IYCEN=IYCEN2
C
      RETURN
      END


	SUBROUTINE GET_BASE_COUNTS(ICOUNTS, IXCEN,IYCEN,IRAD0)
C
	PARAMETER (MAX_NUMX=8000,MAX_NUMY=2500,IUNIT=6)
	COMMON /RIMAGE_COM/ RIMAGE(MAX_NUMX,MAX_NUMY),NUMX,NUMY
C
	IRAD=IRAD0/4
C
	NSUM=0
	SUM=0
	DO IX=IXCEN-IRAD,IXCEN+IRAD
		DO IY=IYCEN-IRAD,IYCEN+IRAD
			IF((IXCEN-IX)**2 + (IYCEN-IY)**2 .LE. IRAD**2) THEN
				NSUM=NSUM+1
				SUM=SUM+RIMAGE(IX,IY)
			ENDIF
		ENDDO
	ENDDO
C
	ICOUNTS=NINT(SUM/MAX(1,NSUM))
C
	RETURN
	END
