	PROGRAM LAUE_TIFF
C
	LOGICAL LASK
	COMMON /LASK_COM/ LASK
C
	CHARACTER FILE_NAME*255
C
	CALL GET_COMMAND_ARGUMENT(1,FILE_NAME,LEN,ISTATUS)
C
	LASK=(ISTATUS .NE. 0)
	IF( LASK ) THEN
	  PRINT '(1X,A,$)','File Name: '
	  READ(*,*) FILE_NAME
	  LEN=LEN_TRIM(FILE_NAME)
	ENDIF
C
C==================================================
C Uncomment to build dump_tiff.exe
CC	CALL DUMP_TIFF(FILE_NAME(1:LEN))
C
C Uncomment to build dump_laue.exe
CC	CALL DUMP_LAUE(FILE_NAME(1:LEN))
C
C Uncomment to build laue_tiff.exe
	CALL LAUE_TIFF2(FILE_NAME(1:LEN))
C
C==================================================
C
	CALL QUIT('')
C
	END


	SUBROUTINE QUIT(TEXT)
C
C Workaround as SCILAB doesn't return STOP messages as they
C go to stderr not stdout
C
	CHARACTER*(*) TEXT
C
	LOGICAL LASK
	COMMON /LASK_COM/ LASK
C
	IF(LEN(TEXT) .GT. 0) PRINT *,TEXT
C
	IF( LASK ) THEN
		PRINT '(/,1X,A,$)','Press return to finish'
		READ(*,'(A)') FILE_NAME
	ENDIF
C
	CALL EXIT()
C
	END


	SUBROUTINE LAUE_TIFF2(FILE_NAME)
C
	CHARACTER FILE_NAME*(*)
C
	CALL READ_TIFF_INFO(ISTATUS,FILE_NAME,2)
C
	IF(ISTATUS .EQ. -1)	CALL QUIT('ERROR: Can''t open file name = '//FILE_NAME)
	IF(ISTATUS .EQ. 1)	CALL QUIT('ERROR: Not a TIF file (Invalid magic numbers)')
	IF(ISTATUS .EQ. 2)	CALL QUIT('ERROR: Invalid IFD offset')
	IF(ISTATUS .EQ. 3)	CALL QUIT('ERROR: Invalid IFD NTAGS')
	IF(ISTATUS .EQ. 11) CALL QUIT('ERROR: Invalid Laue image (apparently an ImageJ copy)')
	IF(ISTATUS .EQ. 12) CALL QUIT('ERROR: Invalid Laue image (big-endian TIF file)')
C
	IF(ISTATUS .GE. 100) PRINT *,'WARNING:',ISTATUS-100,' extra user defined TAGs found'
	CALL PRINT_LAUE_FILE(FILE_NAME)
C
	RETURN
	END

	
	SUBROUTINE PRINT_LAUE_FILE(FILE_NAME)
C
	CHARACTER FILE_NAME*(*)
C
	CHARACTER*10 SADC,SKAPPA
	INTEGER*2 IMAGE(100000000)
C
	CHARACTER*2000 COMMENT,SAMPLE,USER,DATETIME,HOST,BEAM,ADC_INFO
	COMMON /TIFFINFO_COM/ COMMENT,SAMPLE,USER,DATETIME,HOST,BEAM,
	1			IOFF_DATA,NUMX,NUMY,IXYRES,ISTARTX,ISTARTY,ISPEED,
	2			EXPO_TIME,EXPO_PHI,TEMP_BEGIN,TEMP_END,TEMP_MIN,TEMP_MAX,
	3			IADC,ADC_ADD,ADC_DIV,ADC_INFO,IAPER_1,IAPER_2,IKAPPA
C
	PRINT '(1X,2A,2A)','Sample: ',TRIM(SAMPLE),'    Comment: ',TRIM(COMMENT)
	PRINT '(1X,I5,A,I5,A,I4,A,2I4)',NUMX,' x',NUMY,' at',
	1								IXYRES,' microns    Startcoords =',ISTARTX,ISTARTY
	PRINT '(1X,7A)',TRIM(USER),', ',TRIM(HOST),', ',TRIM(BEAM),', ',TRIM(DATETIME)
	PRINT '(1X,A,I5,A,F9.3)','Exposure =',NINT(EXPO_TIME),' s    PHI =',EXPO_PHI
	PRINT '(1X,A,4F7.2,A)','Temp(K) =',TEMP_BEGIN,TEMP_END,TEMP_MIN,TEMP_MAX,
	1							' (start,end,min,max)'
C
	IF(HOST .EQ. 'KOALA2') THEN
		SADC='Gain = 0?'
	  IF(IADC .EQ. 1) SADC='Low Gain'
	  IF(IADC .EQ. 2) SADC='High Gain'
		SKAPPA='OFF'
	  IF(IKAPPA .EQ. 1) SKAPPA='0'
	  IF(IKAPPA .EQ. 2) SKAPPA='42'
		PRINT '(1X,2A,2I3,2A)',TRIM(SADC),' File, Guide Apertures =',
	1													IAPER_1,IAPER_2,', KAPPA = ',TRIM(SKAPPA)
	ENDIF
C
C Simple routine to read IMAGE from a Laue TIFF as a single block
C NB: No error checking is done, it is assumed the file is valid and little-endian
C
	IF(NUMX*NUMY .GT. 100000000) STOP 'ERROR: NUMX*NUMY > 1E8'
	CALL FAST_TIFF_READ(IMAGE, NUMX,NUMY,IOFF_DATA, FILE_NAME)
C
	VMIN=+1E19
	VMAX=-1E19
	VSUM=0.0
	N10K=0
	N30K=0
	N60K=0
	DO I=1,NUMX*NUMY
	  VAL=IMAGE(I)
	  IF(VAL .LT. 0.0) VAL=VAL+65536
	  VMIN=MIN(VMIN, VAL)
	  VMAX=MAX(VMAX, VAL)
	  VSUM=VSUM + VAL
	  IF(VAL .GT. 1.0E4) N10K=N10K+1
	  IF(VAL .GT. 3.0E4) N30K=N30K+1
	  IF(VAL .GT. 6.0E4) N60K=N60K+1
	ENDDO
	PRINT '(1X,A,3(I7,A))','Pixels vs Intensity: ',N10K,' (>10K)',
	1								N30K,' (>30K)',N60K,' (>60K)'
	PRINT '(1X,A,3I7,A)','Intensities =',NINT(VMIN),NINT(VSUM/NUMX/NUMY),
	1								NINT(VMAX),' (min, mean, max)'
C
	RETURN
	END


	SUBROUTINE DUMP_LAUE(FILE_NAME)
C
	CHARACTER FILE_NAME*(*)
C
	CHARACTER STRING*2000
C
	INTEGER*1 BUFFER1(4000)
	COMMON /READ_TIF_COM/ BUFFER1,IREC,IUNIT,ISWAP
C
C Initialise parameters used by TIFF_READ_INT1() which actually reads the file
C
	IREC=-1
	IUNIT=2
	ISWAP=0
C
C Open file by direct access and 4000 byte records (1000 words for Intel)
C
	OPEN(UNIT=IUNIT,FILE=FILE_NAME,STATUS='OLD',
	1       FORM='UNFORMATTED',ACCESS='DIRECT',RECL=1000)
C
C Check magic numbers and TIF is little-endian
C
	CALL TIFF_READ_INT2(IMAGIC,0)
	IF(IMAGIC .EQ. 257*ICHAR('I')) THEN
		PRINT *,'IMAGIC="II": Intel little-endian file'
	ELSEIF(IMAGIC .EQ. 257*ICHAR('M')) THEN
		PRINT *,'IMAGIC="MM": Motorola big-endian file'
	  ISWAP=1
	ELSE
	  PRINT *,'IMAGIC=',IMAGIC
	  STOP 'ERROR: Not a valid TIF file'
	ENDIF
C
	CALL TIFF_READ_INT2(I42,2)
	PRINT *,'I42=',I42
	IF(I42 .NE. 42) STOP 'ERROR: Not a valid TIF file'
C
C Get file offset to the first IFD
C
	CALL TIFF_READ_INT4(IOFF_IFD,4)
	PRINT *,'IOFF_IFD=',IOFF_IFD
	IF(IOFF_IFD .LE. 0) STOP 'ERROR: Invalid IFD offset'
C
C Loop through all records in the IFD
C
	CALL TIFF_READ_INT2(NTAGS,IOFF_IFD)
	PRINT *,'NTAGS=',NTAGS
	IF(NTAGS .LE. 0) STOP 'ERROR: Invalid IFD NTAGS'
	IOFF_IFD=IOFF_IFD+2
	DO ITAG=1,NTAGS
C
C Read and unpack the next record in the IFD
	  CALL TIFF_READ_INT2(ITAG_ID,IOFF_IFD)
	  CALL TIFF_READ_INT2(ITAG_TYPE,IOFF_IFD+2)
	  CALL TIFF_READ_INT4(ITAG_COUNT,IOFF_IFD+4)
	  CALL TIFF_READ_INT2(ITAG_VAL2,IOFF_IFD+8)
	  CALL TIFF_READ_INT4(ITAG_VAL4,IOFF_IFD+8)
	  ITAG_OFFSET=ITAG_VAL4		! the last I4 may also be an offset
C Create the value (STRING, VALUE) depending on ITAG_TYPE
	  IF(ITAG_TYPE .EQ. 2) THEN
	    CALL TIFF_GET_STRING(STRING,ITAG_OFFSET,ITAG_COUNT)
	    READ(STRING,'(F20.0)',IOSTAT=IDUMMY) VALUE
	  ELSE IF(ITAG_TYPE .EQ. 3) THEN
	    VALUE=ITAG_VAL2
	  ELSE IF(ITAG_TYPE .EQ. 4) THEN
	    VALUE=ITAG_VAL4
	  ELSE IF(ITAG_TYPE .EQ. 5) THEN
	    CALL TIFF_GET_RATIONAL(VALUE,ITAG_OFFSET)
	  ELSE IF(ITAG_TYPE .EQ. 12) THEN
	    CALL TIFF_GET_DOUBLE(VALUE,ITAG_OFFSET)
	  ENDIF
C
C Output some of the general TIFF tags
	  IF     (ITAG_ID .EQ. 256) THEN
	    PRINT *,'NUMX=',NINT(VALUE)
	  ELSE IF(ITAG_ID .EQ. 257) THEN
	    PRINT *,'NUMY=',NINT(VALUE)
	  ELSE IF(ITAG_ID .EQ. 273) THEN
C If count=1, the data offset is IVAL4, else stored as an array and have to read value
	    IF(ITAG_COUNT .EQ. 1) THEN
	      IOFF_DATA=ITAG_OFFSET
	    ELSE
	      CALL TIFF_READ_INT4(IOFF_DATA,ITAG_OFFSET)
	    ENDIF
	    PRINT *,'IOFF_DATA=',IOFF_DATA
	  ELSE IF(ITAG_ID .EQ. 270) THEN
	    PRINT *,'COMMENT=',TRIM(STRING)
	  ELSE IF(ITAG_ID.EQ.282) THEN
	    PRINT *,'IXYRES=',NINT(1E4*VALUE)
	  ELSE IF(ITAG_ID.EQ.286) THEN
	    PRINT *,'ISTARTX=',NINT(VALUE)
	  ELSE IF(ITAG_ID.EQ.287) THEN
	    PRINT *,'ISTARTY=',NINT(VALUE)
	  ELSE IF(ITAG_ID .EQ. 306) THEN
C Convert date to a 24 hour Australian format
	    CALL CONVERT_DATE_TIME(STRING,ITAG_COUNT)
	    PRINT *,'DATETIME=',TRIM(STRING)
	  ELSE IF(ITAG_ID .EQ. 315) THEN
	    PRINT *,'USER=',TRIM(STRING)
	  ELSE IF(ITAG_ID .EQ. 316) THEN
	    PRINT *,'HOST=',TRIM(STRING)
C
C Output user defined tags
	  ELSE IF(ITAG_ID .EQ. 1000) THEN
	    PRINT *,'TEMP_BEGIN=',VALUE
	  ELSE IF(ITAG_ID .EQ. 1001) THEN
	    PRINT *,'TEMP_END=',VALUE
	  ELSE IF(ITAG_ID .EQ. 1002) THEN
	    PRINT *,'SAMPLE=',TRIM(STRING)
	  ELSE IF(ITAG_ID .EQ. 1003) THEN
	    PRINT *,'EXPO_TIME=',VALUE
	  ELSE IF(ITAG_ID .EQ. 1004) THEN
	    PRINT *,'EXPO_PHI=',VALUE
	  ELSE IF(ITAG_ID .EQ. 1005) THEN
	    PRINT *,'ISTARTX=',NINT(VALUE)
	  ELSE IF(ITAG_ID .EQ. 1006) THEN
	    PRINT *,'ISTARTY=',NINT(VALUE)
	  ELSE IF(ITAG_ID .EQ. 1007) THEN
	    PRINT *,'ISPEED=',NINT(VALUE)
	  ELSE IF(ITAG_ID .EQ. 1008) THEN
	    PRINT *,'TEMP_MIN=',VALUE
	  ELSE IF(ITAG_ID .EQ. 1009) THEN
	    PRINT *,'TEMP_MAX=',VALUE
	  ELSE IF(ITAG_ID .EQ. 1010) THEN
	    PRINT *,'BEAM=',TRIM(STRING)
	  ELSE IF(ITAG_ID .EQ. 1011) THEN
	    PRINT *,'IADC=',NINT(VALUE)
	  ELSE IF(ITAG_ID .EQ. 1012) THEN
	    PRINT *,'ADC_ADD=',VALUE
	  ELSE IF(ITAG_ID .EQ. 1013) THEN
	    PRINT *,'ADC_DIV=',VALUE
	  ELSE IF(ITAG_ID .EQ. 1014) THEN
	    PRINT *,'IAPER_1=',NINT(VALUE)
	  ELSE IF(ITAG_ID .EQ. 1015) THEN
	    PRINT *,'IAPER_2=',NINT(VALUE)
	  ELSE IF(ITAG_ID .EQ. 1016) THEN
	    PRINT *,'ADC_INFO=',TRIM(STRING)
	  ELSE IF(ITAG_ID .EQ. 1017) THEN
	    PRINT *,'IKAPPA=',NINT(VALUE)
C
C Output unknown user defined tags
	  ELSE IF(ITAG_ID .GE. 1000) THEN
	    IF(ITAG_TYPE .EQ. 2) THEN
	      PRINT *,'TAG(',ITAG_ID,')="',TRIM(STRING),'"'
	    ELSEIF(ITAG_TYPE .LE. 4) THEN
	      PRINT *,'TAG(',ITAG_ID,')=',NINT(VALUE)
	    ELSE
	      PRINT *,'TAG(',ITAG_ID,')=',VALUE
	    ENDIF
	  ENDIF
C
C Advance the offset to the next IFD record, then loop back
	  IOFF_IFD=IOFF_IFD+12
	ENDDO
C
	CLOSE(UNIT=IUNIT)
	RETURN
C
	END



	SUBROUTINE DUMP_TIFF(FILE_NAME)
C
	CHARACTER FILE_NAME*(*)
C
	CHARACTER STRING*2000
C
	INTEGER*1 BUFFER1(4000)
	COMMON /READ_TIF_COM/ BUFFER1,IREC,IUNIT,ISWAP
C
C Initialise parameters used by TIFF_READ_INT1() which actually reads the file
C
	IREC=-1
	IUNIT=2
	ISWAP=0
C
C Open file by direct access and 4000 byte records (1000 words for Intel)
C
	OPEN(UNIT=IUNIT,FILE=FILE_NAME,STATUS='OLD',
	1       FORM='UNFORMATTED',ACCESS='DIRECT',RECL=1000)
C
C Check if a little-endian TIF
C
	CALL TIFF_READ_INT2(IMAGIC,0)
	PRINT *,'IMAGIC=',IMAGIC
	IF(IMAGIC .EQ. 257*ICHAR('I')) THEN
		PRINT *,'IMAGIC="II": Intel little-endian file'
	ELSEIF(IMAGIC .EQ. 257*ICHAR('M')) THEN
		PRINT *,'IMAGIC="MM": Motorola big-endian file'
	  ISWAP=1
	ELSE
	  STOP 'ERROR: Not a valid TIF file'
	ENDIF
	CALL TIFF_READ_INT2(I42,2)
	PRINT *,'I42=',I42
	IF(I42 .NE. 42) STOP 'ERROR: Not a TIF file (Invalid magic number)'
C
C Get file offset to the first IFD
C
	CALL TIFF_READ_INT4(IOFF_IFD,4)
	PRINT *,'IOFF_IFD=',IOFF_IFD
	IF(IOFF_IFD .LE. 0) STOP 'ERROR: Invalid IFD offset'
C
C Loop through all records in the IFD
C
	CALL TIFF_READ_INT2(NTAGS,IOFF_IFD)
	PRINT *,'NTAGS=',NTAGS
	IF(NTAGS .LE. 0) STOP 'ERROR: Invalid IFD NTAGS'
	IOFF_IFD=IOFF_IFD+2
	DO ITAG=1,NTAGS
C
C Read and unpack the next record in the IFD
	  CALL TIFF_READ_INT2(ITAG_ID,IOFF_IFD)
	  CALL TIFF_READ_INT2(ITAG_TYPE,IOFF_IFD+2)
	  CALL TIFF_READ_INT4(ITAG_COUNT,IOFF_IFD+4)
	  CALL TIFF_READ_INT2(ITAG_VAL2,IOFF_IFD+8)
	  CALL TIFF_READ_INT4(ITAG_VAL4,IOFF_IFD+8)
	  ITAG_OFFSET=ITAG_VAL4		! the last I4 may also be an offset
C Create the value (STRING, VALUE) depending on ITAG_TYPE
	  IF(ITAG_TYPE .EQ. 2) THEN
	    CALL TIFF_GET_STRING(STRING,ITAG_OFFSET,ITAG_COUNT)
	    PRINT *,'ITAG_ID=',ITAG_ID,'Str:',TRIM(STRING)
	  ELSE IF(ITAG_TYPE .EQ. 3) THEN
	    PRINT *,'ITAG_ID=',ITAG_ID,'I2 :',ITAG_VAL2
	  ELSE IF(ITAG_TYPE .EQ. 4) THEN
	    PRINT *,'ITAG_ID=',ITAG_ID,'I4 :',ITAG_VAL4
	  ELSE IF(ITAG_TYPE .EQ. 5) THEN
	    CALL TIFF_GET_RATIONAL(VALUE,ITAG_OFFSET)
	    PRINT *,'ITAG_ID=',ITAG_ID,'RAT:',VALUE
	  ELSE IF(ITAG_TYPE .EQ. 12) THEN
	    CALL TIFF_GET_DOUBLE(VALUE,ITAG_OFFSET)
	    PRINT *,'ITAG_ID=',ITAG_ID,'R8: ',VALUE
	  ELSE
	    PRINT *,'ITAG_ID=',ITAG_ID,'Unimplemented Type=',ITAG_TYPE
	  ENDIF

	  IF(ITAG_ID .EQ. 273) THEN
C If count=1, the data offset is IVAL4, else stored as an array and have to read value
	    IF(ITAG_COUNT .EQ. 1) THEN
	      IOFF_DATA=ITAG_OFFSET
	    ELSE
	      CALL TIFF_READ_INT4(IOFF_DATA,ITAG_OFFSET)
	    ENDIF
	    PRINT *,'IOFF_DATA=',IOFF_DATA
	  ENDIF
C
C Advance the offset to the next IFD record, then loop back
	  IOFF_IFD=IOFF_IFD+12
	ENDDO
C
	CLOSE(UNIT=IUNIT)
	RETURN
C
	END



